### ISSUE TITLE
Paywall Link

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#10]
[Paywall Link](https://paywall.link/) is a Lightning Paywall Generator.

Section: Spend-BTC & Get-BTC

**Comment by 6102bitcoin** [comment]
Generally low quality content at the moment.
Will observe

**Comment by joe-rodgers** [comment]
I fired this up last night, and I am always impressed when tools work as advertised. I think this will be a really cool project when he has a paywall button like tippin.me and even "templetized" paywall landing pages.

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/a97082dbbc4f9fa0929f1a527c720457aaf82949)
