### ISSUE TITLE
Content Suggestion: River Financial

### ISSUE THREAD

**Issue by ecurrencyhodler** [bitcoin-only/bitcoin-only#100]
1) Link to Content: https://river.com/
2) Briefly Describe Content: The best place to buy, sell, and use Bitcoin for the long-term investor.
3) Suggested Section: In the "Get Bitcoin" then "Buy" section. We currently serve only the United States.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/0c838234db10bbb9ec4d1484e43c4cd7cdf4acf3)

Apologies for the long delay!
