### ISSUE TITLE
Learn Bitcoin - The Easy Way

### ISSUE THREAD

**Issue by bitcoinembassylondon** [bitcoin-only/bitcoin-only#103]
1. Name of Meetup: Learn Bitcoin - The Easy Way
2.  Location Of Meetup: London, England
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/Bitcoin-Embassy-London/events/267134813/
- Telegram Group (or similar): 
- Website: http://bitcoinembassylondon.com

**Comment by 6102bitcoin** [comment]
Do you have a twitter handle of the organiser?
PS. Heads up the https on your website isn't working.

**Comment by bitcoinembassylondon** [comment]
Yes. I am the organiser

Its @leifcid

Thanks for the heads up on the https

Regards
Leif Cid (ex shitcoiner )
.
.
.

On Friday, January 24, 2020, 6102bitcoin <notifications@github.com> wrote:
> Do you have a twitter handle of the organiser?
> PS. Heads up the https on your website isn't working.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/OpkKZmq4OD-MgE8vyXvuW-LmcGWP3LDjJMQoTVP51OdDSiATPIYeeXwN51VpL7QTc5V-NqryOjCV7CmjayPuUujB1VxMkcEBgvBDZVgamkcuahsRf2Os8THh1cL0MzxEXjrHAYHBMij964aeBCKzicrgJ7E3kaE5AOQvOEJuQKbehRgGA_xCU2CmdPbE1oVKercAhfqMjJNvXvHAsWA4YRfjohdKUfaFxVsqeBwucw=s0-d-e1-ft#https://github.com/notifications/beacon/AOAXFGCU7MVLA7EZMUE7EXLQ7MXPBA5CNFSM4JZ6DFRKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ3VNJQ.gif>

**Comment by 6102bitcoin** [comment]
[Added]
