### ISSUE TITLE
Content Suggestion: Bitcoin articles and books, translated into Russian

### ISSUE THREAD

**Issue by LightningTony** [bitcoin-only/bitcoin-only#104]
1) Link to Content: https://bitcoin-translated.ru/
2) Briefly Describe Content: Articles and books written by the prominent bitcoiners, translated into Russian.
3) Suggested Section: Learning

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/46b4f0f59088747ec62f299ae06b0f76db55dbb5)

Apologies for the delay!
