### ISSUE TITLE
Content Suggestion: NAME OF CONTENT TO BE ADDED

### ISSUE THREAD

**Issue by coinicarus** [bitcoin-only/bitcoin-only#105]
1) Link to Content: https://anchor.fm/funwithbitcoin

2) Briefly Describe Content: This Podcast series discusses a wide range of bitcoin only related topics ranging from layering solutions, culture ; social media aspects of bitcoin. We also do interviews with a wide range of bitcoin enthusiasts. We hold a once monthly lightning node roundtable where developers from all over the lightning community get together and chat about updates, answer questions, discuss lightning nodes and their related technology.

3) Suggested Section: podcasts

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/dad98b7fd12d88c8b9e2d7096c4d570c7b4512b0)

**Comment by coinicarus** [comment]
thank you! :)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
