### ISSUE TITLE
Update Suggestion: Add CryptoCloaks (Now Bitcoin Only)

### ISSUE THREAD

**Issue by CryptoCloaks** [bitcoin-only/bitcoin-only#109]
*Looking to get added to Bitcoin-Only, it's long overdue for us!**

Starting today, we have officially move to Bitcoin only for receiving payments besides Dirty Fiat. 
As we prepare for 2020 it made the most financial sense for us. There we're two main factors that came into play.

1) A very low amount of orders in any currency besides BTC/USD
2) 85% of the orders we received in any currency besides BTC/USD are in red. (In some cases they are 15% of what the initial sale was.)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/c5ec84c4c56cb72ed8dd3822027b15aa6b9c174d)

Now all that's left is to change your name to BitcoinCloaks!
