### ISSUE TITLE
Add JoinMarket

### ISSUE THREAD

**Issue by kristapsk** [bitcoin-only/bitcoin-only#11]
[JoinMarket](https://github.com/JoinMarket-Org/joinmarket-clientserver) is a CoinJoin software, which includes a wallet.

**Comment by kristapsk** [comment]
Sorry, could not figure out how to add label when creating issue. It didn't show me the label selection (it does for my own github repos).

**Comment by 6102bitcoin** [comment]
Joinmarket is listed on the [privacy page](https://bitcoin-only.com/#privacy). 

I assume your suggestion is adding it to the wallets page?

We could add a link to the privacy page in the 'advanced' section of the wallets page.

Ps. There should be labels available

**Comment by kristapsk** [comment]
> I assume your suggestion is adding it to the wallets page?

Yes, that was idea.

> Ps. There should be labels available

That's how "new issue" in this project looks for me (notice new label selection etc on the right):

![image](https://user-images.githubusercontent.com/4500994/64762368-bb669500-d546-11e9-9121-11c52c7e0753.png)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/8b7315300627af07054fd54ed03181f422c80520) Privacy Page link to wallets page intro
