### ISSUE TITLE
Graaf One

### ISSUE THREAD

**Issue by Dolzhenko** [bitcoin-only/bitcoin-only#112]
**Please Describe Suggested Update:**
Please add "Graaf One" under the Buy section for Canada.

It's a non-custodial Lightning Network brokerage, you can put the description as: _"Buy and Sell via the Lightning Network"_

https://www.graaf.one/

Thank you

**Comment by 6102bitcoin** [comment]
Waiting on [twitter feedback](https://twitter.com/6102bitcoin/status/1246459710800375817)

**Comment by 6102bitcoin** [comment]
[Requested](https://twitter.com/6102bitcoin/status/1302666676295675905) some feedback from users.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/12328b6d8191ad436a238b9d24b9164adafec617)
