### ISSUE TITLE
AddContent Suggestion: Bitcoin ATM's to Get Bitcoin

### ISSUE THREAD

**Issue by DiverterBTC** [bitcoin-only/bitcoin-only#116]
1) Link to Content: https://coinatmradar.com/
2) Briefly Describe Content: Provides locations of Bitcoin ATM's in users area to buy Bitcoin
3) Suggested Section: Suggest checking verification information of ATM before visiting due to differences in verification/KYC requirements to ensure more private purchasing of BTC. There are often other coins offered at ATM's, but the privacy enhancing feature of being able to buy <$900 of BTC using only SMS verification (burner) and Name (any name) is too much to overlook imo.

**Comment by pardus79** [comment]
This site is not bitcoin only. They provide info to look specifically for atms that sell altcoins.

Example: https://coinatmradar.com/ether-atm-map/

**Comment by 6102bitcoin** [comment]
Thanks Pardus
