### ISSUE TITLE
Content Suggestion: LibertyMugs.com

### ISSUE THREAD

**Issue by rollomcfloogle** [bitcoin-only/bitcoin-only#122]
1) Link to Content: https://www.libertymugs.com
2) Briefly Describe Content: Mugs and T-shirt using BTCPayServer
3) Suggested Section: Spend Bitcoin

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/06689b997e642180fe545c6a970574bb6dd3c773)
