### ISSUE TITLE
Meetup Suggestion: Bitcoin Sheffield

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#123]
1. Name of meetup: Bitcoin Sheffield
2.  Location Of Meetup: Sheffield, UK
3. At least one of the following:
- Website: http://bitcoinsheffield.co.uk/

## Optional 
- Name of Organiser(s) & Twitter Handle: @in3rsha

**Comment by in3rsha** [comment]
Thanks, would be great to have Bitcoin Sheffield listed as a meetup. Is there anything you need from me?

I can confirm the group is bitcoin-only. I am not against other coins (I am mostly interested in the technology of cryptocurrency), but I do focus on Bitcoin solely and I'm cautious about the promotion of scams.

**Comment by 6102bitcoin** [comment]
Nothing you need to do - it's on the list, I just need to wade through all these issues this weekend and get up to date.

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/1db1800a4b44a74c3564a2914f559b9fd561d632)
