### ISSUE TITLE
Content Suggestion: NAME OF CONTENT TO BE ADDED

### ISSUE THREAD

**Issue by GaryLeland** [bitcoin-only/bitcoin-only#124]
1) Link to Content: https://CryptoCousins.com
2) Briefly Describe Content: Hall OF Fame podcaster Gary Leland produces the  Crypto Cousins weekly to  bring you some of the the best minds in Bitcoin. New episodes are uploaded every Tuesday and reach listeners in over 100 countries.
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Currently ineligible: Scrolling banner of altcoins makes website not bitcoin only.

How do you feel about this interview now?
https://cryptocousins.com/richard-heart/
