### ISSUE TITLE
Content Suggestion: 4 Minute Crypto Show

### ISSUE THREAD

**Issue by GaryLeland** [bitcoin-only/bitcoin-only#125]
1) Link to Content: PASTE URL HERE https://4MinuteCrypto.com
2) Briefly Describe Content: If you want to keep up to date with whats happening in the world of Bitcoin then you will love the 4 Minute Crypto Show.
As the name suggest these short, 4 minute or less shows are quick and sweet.
Join Gary Leland for 1 Bitcoin news story five days a week.
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Again, scrolling banner of altcoins means website is not bitcoin only.
