### ISSUE TITLE
Georgetown Bitcoin Meetup

### ISSUE THREAD

**Issue by Pillagr** [bitcoin-only/bitcoin-only#126]
1) Link to Content: https://www.eventbrite.com/e/georgetown-bitcoin-meetup-tickets-84828150281
2) Briefly Describe Content: A biweekly meetup at Georgetown University. Focused on Bitcoin and Lightning. We are mostly focused on introducing and educating new members, but all skill levels are welcome. A few of us are working on Bitcoin or Lightning projects (hardware and software). 
3) Suggested Section: Meetups

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/62ee852647b0970eec3b292e4f458a1a4324187f)

Thank you for your patience.
