### ISSUE TITLE
Meetup Suggestion: Little Rock

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#129]
## Required:
1. Name of Meetup:  Bitcoin Little Rock
2.  Location Of Meetup: Little Rock, AR (USA)
3. At least one of the following:
- Meetup Page: https://twitter.com/_joerodgers/status/1220186941368557575

**Comment by joe-rodgers** [comment]
PR submitted here:

https://github.com/bitcoin-only/bitcoin-only/pull/128

**Comment by 6102bitcoin** [comment]
Added
