### ISSUE TITLE
Content Suggestion: "Le Coin de Table" (Discover Bitcoin while playing) Card game

### ISSUE THREAD

**Issue by bigcoincoin** [bitcoin-only/bitcoin-only#134]
1) Link to Content:  [(http://www.maximalist.ovh/)](url)

2) Briefly Describe Content: 
Board game to discover the Bitcoin universe while having fun.
From 2 to 4 people.

Be the first to build a complete chain of the 5 yellow cards.
Red cards make you lose cards (bitcoin or fiat money).
With the EXCHANGE card, you can quickly exchange your FIAT MONEY for Bitcoin. When the CRISIS card arrives, the FIAT MONEY is worthless for all players and goes in the trash.

Rules included: English, French, Italian, Spanish, German. (Portuges soon).
the game is already use for play but also as a classroom lesson material.

3) Suggested Section: spend bitcoin / fun and play

See the game on the website http://www.maximalist.ovh/

**Comment by pardus79** [comment]
This site accepts altcoins for payment.

**Comment by 6102bitcoin** [comment]
Thanks Pardus.

@bigcoincoin Unfortunatley this site is not suitable for listing. 
- Altcoin Payment
- Affiliate links to Ledger & Coinbase (Both market altcoins to newcomers)
