### ISSUE TITLE
Meetup Suggestion: Portland Bitcoin+Pizza: Free 101 Talk + Open Discussion (1st Mondays)

### ISSUE THREAD

**Issue by Jestopher-BTC** [bitcoin-only/bitcoin-only#135]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoin+Pizza: Free 101 Talk + Open Discussion (1st Mondays)
2.  Location Of Meetup: Flying Pie Pizza 7804 SE Stark St, Portland, OR
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/Portland-Bitcoin-Group/
- Telegram Group (or similar): [please ask an organizer]
- Website: portlandbitcoinconference.com

## Optional 
- Name of Organiser(s) & Twitter Handle: @LiberatingLover @Jestopher_BTC
- Links showing public support: >>>  
https://twitter.com/Jestopher_BTC/status/1181460599059992577?s=20
https://twitter.com/BitConsultants/status/1179830273652842496?s=20

```
As the organiser of Bitcoin+Pizza Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/a2b690398270672b5df20f5e14ad97db9d3ae54c)

Apologies for the delay - best of luck
