### ISSUE TITLE
Content Suggestion: DIYnodes.com

### ISSUE THREAD

**Issue by openoms** [bitcoin-only/bitcoin-only#136]
1) Link to Content: DIYnodes.com
2) Briefly Describe Content: Bitcoin and Lightning nodes, parts and accessories
3) Suggested Section: STORES

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/8afe8d9cee6f2df43d5af4d1eb5798f66cffaeb3)

Thanks for your patience
