### ISSUE TITLE
Content Suggestion: Bitcoin Rapid-Fire by John Vallis

### ISSUE THREAD

**Issue by psychedelicbart** [bitcoin-only/bitcoin-only#137]
1) Link to Content: https://anchor.fm/john-vallis
2) Briefly Describe Content: "Bitcoin is the future of money, that is my firm belief. In this show, I speak with the amazing people who are building and contributing to this revolutionary new industry. The 'rapid-fire' episodes give you some concise info and insights, the 'further discussion' episodes let you listen in on a more casual and open dialogue with each guest."
3) Suggested Section: https://bitcoin-only.com/#podcasts

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/3245b93209a590d694d4c84efae9cb8e1199b417)

Thanks Barto
