### ISSUE TITLE
Melbourne Bitcoin Only

### ISSUE THREAD

**Issue by satoshimacro** [bitcoin-only/bitcoin-only#141]
Hi,
Melbourne Bitcoin-Only is active on your site already.
We have had our organiser move away from Melbourne so I would like to request an update.
Please update the organiser to @BitcoinMEL or @satoshimacro
We are still proudly 100% Bitcoin-Only.
Thanks
Love your work

**Comment by 6102bitcoin** [comment]
[Done!](https://github.com/bitcoin-only/bitcoin-only/commit/5b9aa80641513460fc5ebd07acea5bec315a8674)

**Comment by 6102bitcoin** [comment]
Thanks for the kind words
