### ISSUE TITLE
Content Suggestion: Bitcoin Basics Podcast

### ISSUE THREAD

**Issue by proofofgeek** [bitcoin-only/bitcoin-only#143]
1) Link to Content: https://www.youtube.com/playlist?list=PL81X0bJURmxUdWXCSNtoiFe4vVR9DGZ8Z & http://bitcoinbasicspodcast.com
2) Briefly Describe Content: A bitcoin podcast for beginners, either no-coiners or those recently bought bitcoin but left them on exchanges, which explains the technical, economic and fundamentals of Bitcoin for the everyday person who doesn't live and breathe Bitcoin (like us). "Invest in your own education before investing in Bitcoin".
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/ba56a8c9125e01eb8a580fe072332fed1d6f1013)

Great work! Thanks for your patience.
