### ISSUE TITLE
Content Suggestion: Satstreet

### ISSUE THREAD

**Issue by jonsats** [bitcoin-only/bitcoin-only#147]
1) Link to Content: https://www.satstreet.com/
2) Briefly Describe Content: Satstreet is a new custodial solution for gifting Bitcoin. You can send as little as 1 sat to any email address.
3) Suggested Section: Custodial Bitcoin Wallets

**Comment by pardus79** [comment]
Service is currently bitcoin-only, but per their terms, they appear to be open to adding altcoins:

"5. Satstreet Services

Satstreet provides a way to store, use and manage Bitcoin and any other supported Digital Assets designated by Satstreet. At present, Bitcoin is the only supported Digital Asset, although we reserve the right to add other assets over time."

**Comment by 6102bitcoin** [comment]
@jonsats Do you have any plans to add altcoins?

**Comment by 6102bitcoin** [comment]
Duplicate
