### ISSUE TITLE
Content Suggestion: Satstreet

### ISSUE THREAD

**Issue by jonsats** [bitcoin-only/bitcoin-only#148]
1) Link to Content: https://www.satstreet.com/
2) Briefly Describe Content: Bitcoin Cashback Rewards. Earn Sats Back with account registrations and online purchases.
3) Suggested Section: https://bitcoin-only.com/#get-bitcoin

**Comment by pardus79** [comment]
Service is currently bitcoin-only, but per their terms, they appear to be open to adding altcoins:

"5. Satstreet Services

Satstreet provides a way to store, use and manage Bitcoin and any other supported Digital Assets designated by Satstreet. At present, Bitcoin is the only supported Digital Asset, although we reserve the right to add other assets over time."

**Comment by jonsats** [comment]
The company's sole mission is to drive Bitcoin adoption.
https://medium.com/satstreet

**Comment by 6102bitcoin** [comment]
Sent [tweet](https://twitter.com/BitcoinOnly_/status/1340424873282297856) asking for feedback.

**Comment by 6102bitcoin** [comment]
No feedback after 10 days. Closing issue.
