### ISSUE TITLE
Note opennode is KYC now

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#15]
In Store tools section, make a note for people that opennode is now requiring KYC.

**Comment by PuraVlda** [comment]
Made pull request with KYC note

**Comment by 6102bitcoin** [comment]
Pull request merged some time ago - New [commit](https://github.com/bitcoin-only/bitcoin-only/commit/4de224392a746d6295d89d7f9ea6e3cfb6226c40) clarifies that this is for the merchant (not the payee)
