### ISSUE TITLE
Content Suggestion: BitcoinersBest

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#150]
1) Link to Content: https://bitcoiners.best/
2) Briefly Describe Content: Bitcoin Content Ranking 
3) Suggested Section: Spend Bitcoin

**Comment by 6102bitcoin** [comment]
Currently Down - Will check again

**Comment by pardus79** [comment]
Site still down. Twitter inactive since March.

Closing.
