### ISSUE TITLE
Content Suggestion: Clark Moody Bitcoin Dashboard

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#155]
1) Link to Content: https://bitcoin.clarkmoody.com/dashboard/
2) Briefly Describe Content: Bitcoin & LN metrics
3) Suggested Section: Network Page

Not sure this fits under Explorers or Fees. Maybe a new subcategory Metrics (or something like that) on this page?

**Comment by MaxSikorski** [comment]
Yes. I believe https://bitcoin.clarkmoody.com/dashboard/ should be listed under new subcategory called Metrics. 

Is there a better name than Metrics?

**Comment by 6102bitcoin** [comment]
It's a good idea. It is a bit more work to make a new section but this would be good.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/a076530a76e3b9708c09751e80b57aec1ec4f1ca?diff=unified) 

Cheers!
