### ISSUE TITLE
Content Suggestion: GiveBitcoin.io

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#156]
1) Link to Content: https://givebitcoin.io/
2) Briefly Describe Content: Site for gifting bitcoin and educating nocoiners. Receiver receives btc in the future and education up until btc is released to them. Is custodial.
3) Suggested Section: Get Bitcoin. Maybe also Education.

**Comment by 6102bitcoin** [comment]
Fees don't seem to make sense - I have reached out to them for clarification.

"Our fee is is $2 or 2% of the gifted amount, whichever is smaller. "
yet
"The fee for a $500 gift is $10."

[Source](https://help.swanbitcoin.com/hc/en-us/articles/360039084794-How-do-GiveBitcoin-Fees-Work-)

**Comment by pardus79** [comment]
Don't know if they changed it since you posted, but it now says "Our fee is 2% of the gifted amount, with a $2 minimum." This makes more sense.

The $10 fee for $500 is 2%.

**Comment by pardus79** [comment]
Still waiting for more info on this @6102bitcoin? I think they clarified the fee issue.

**Comment by 6102bitcoin** [comment]
Looks good!
