### ISSUE TITLE
Add pollofeed.com

### ISSUE THREAD

**Issue by j-chimienti** [bitcoin-only/bitcoin-only#16]
pollofeed.com is a chicken feeder powered by bitcoin lightning.

It showcases the instant transactions capabilities of lightning, and how we can utilize lightning to control remote objects in the real world

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/02e97a281e3a59c64f873956f8f8cf40d9acefec)

Thanks for the suggestion!
