### ISSUE TITLE
https://radvladdy.com

### ISSUE THREAD

**Issue by RadVladdy** [bitcoin-only/bitcoin-only#161]
1) https://radvladdy.com
2) RadVladdy - All about Bitcoin.  A bitcoin educational site for educating family and friends.
3) Information is organized in a way to introduce the beginner to bitcoin and then walks them through educational material to intermediate, then advanced Bitcoin material.  Also a blog with important bitcoin news, re-posting/re-tweeting important recent bitcoin content from Twitter and the web. Links to recommended products or services are most often referral/affiliate links to help support the costs of the website.

**Comment by 6102bitcoin** [comment]
Thanks for the suggestion - Can you add a note explaining that your links to exchanges etc. are referral links?

**Comment by RadVladdy** [comment]
Done. Thanks for your consideration.

**Comment by 6102bitcoin** [comment]
Just checked - No indication of referral links. Closing now.
