### ISSUE TITLE
Meetup Suggestion: Toledo Bitcoin Meetup Group

### ISSUE THREAD

**Issue by MaxSikorski** [bitcoin-only/bitcoin-only#164]
(I am new to GitHub and learning to use it appropriately for contributions. Please bear with me. Thank you.)

## Required:
1. Name of Meetup: Toledo Bitcoin
2.  Location Of Meetup: Toledo, Ohio, USA
3. At least one of the following: 
- Telegram Group: https://www.t.me/toledobitcoin
- Twitter: https://twitter.com/toledobitcoin
- Website: https://toledobitcoin.wordpress.com, https://toledobitcoin.io
- Meetup Page: https://www.meetup.com/Toledo-Bitcoin-Meetup-Group/

## Optional 
- Name of Organiser(s) & Twitter Handle: Max Sikorski, Twitter: @ MaxwellSikorski
- Links showing public support: >>>  
https://twitter.com/MaxwellSikorski/status/1232133160353370112

**Comment by MaxSikorski** [comment]
Just a reminder for potential merge :)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/6d16bd978016a927dfcd75ea8358179b1bdb649d)

Apologies for the delay - Thank you for your patience!
