### ISSUE TITLE
Content Suggestion: Swan Bitcoin

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#168]
1) Link to Content: https://www.swanbitcoin.com/
2) Briefly Describe Content: Exchange for buying bitcoin on a recurring schedule.
3) Suggested Section: Get Bitcoin - Buy

Hasn't officially launched yet. Suggest waiting until launched.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/552179d3661f363138e49d370eb0e31eb06f6a39)
