### ISSUE TITLE
Content Suggestion: Strike

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#169]
1) Link to Content: https://strike.zaphq.io/
2) Briefly Describe Content: Buy LN bitcoin.
3) Suggested Section: Get Bitcoin - Buy

More info: https://medium.com/@JimmyMow/announcing-strike-by-zap-4f578c7c8984

Still in beta. Recommend waiting until launch to add.

**Comment by 6102bitcoin** [comment]
Sounds good - Wait till launch

**Comment by pardus79** [comment]
Launched today.

Should it also go in Spend Bitcoin>Tools? Bullbitcoin is also there.
