### ISSUE TITLE
Add Bitcoin News by Lightning Hood Medium Article

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#17]
Would like to add the Lightning Hood Medium Article to bitcoin-only.  Weekly article we write up then base our podcast off of.  Gather Bitcoin and Lightning Related news on a weekly Basis.

**Disregard  

> #article Logo for a few in July, somehow some Publisher (Altcoin Magazine) linked their logo to our Article and we didn't realize the issue for a few weeks then corrected**

https://medium.com/@lightninghood

**Comment by PuraVlda** [comment]
Created Pull Request

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/pull/25)
