### ISSUE TITLE
Content Suggestion: Bitcoin Lessons

### ISSUE THREAD

**Issue by BitcoinLessons** [bitcoin-only/bitcoin-only#170]
1) Link to Content: https://www.bitcoinlessons.org/ 
2) Briefly Describe Content: An education app for iOS and Android to help newcomers answer the question 'why bitcoin'.
3) Suggested Section: Learning

**Comment by 6102bitcoin** [comment]
Please can you send me a full copy of the lessons to review. 
sixoneohtwo@protonmail.com

**Comment by BitcoinLessons** [comment]
Sure, this isn’t the exact text in the app as we’ve made changes based on feedback already, but this is 95% the content in the app and the best way we can share the lesson content with you outside of the app itself.  The live content is buried in a CMS and much harder to share.

http://www.bitcoinapedia.com/lessons/ <http://www.bitcoinapedia.com/lessons/>

**Comment by 6102bitcoin** [comment]
Lesson 8
> There are plenty of Alt coins that are not trying to solve the problem of sound money for the globe and do not compete directly 
with Bitcoin.

I think people could interpret this as support.

**Comment by BitcoinLessons** [comment]
Our view is this is a factually correct statement that acknowledges their existence where later we describe how they have nothing to do with bitcoin and so we will not be going into them in any detail.  

We’ve tried to stay away from terms like shitcoin purely to allow us to not get flagged by the platform censorship.

**Comment by 6102bitcoin** [comment]
What is to be gained by such a generic statement? Personally I wouldn't recommend anyone waste time evaluating non-monetary altcoins

**Comment by BitcoinLessons** [comment]
Purely to acknowledge they exist.  Our users are likely very new so may have not come across shitcoins at all yet, but we know they will so we spend some time comparing the pro’s/con’s of the best known coins that compete with bitcoin but we openly dismiss the rest by comparing them to banana’s, which are also irrelevant when learning about bitcoin.

We aren’t encouraging they investigate them, just letting them know they exist and are irrelevant so when they do find them in the future they have some level of context and it isn’t a surprise which they may feel like exploring by falling down the ‘blockchain not bitcoin’ trap.

**Comment by 6102bitcoin** [comment]
It sounds like you are positive about some non monetary altcoins. Can you give a example of one you think is not a scam?

**Comment by BitcoinLessons** [comment]
No, we are not positive about any coins other than bitcoin. We are bitcoin only and always will be.
    	
    	
    
  
 From: 6102bitcoin <notifications@github.com>Sent: Wednesday, December 23, 2020 22:42To: bitcoin-only/bitcoin-onlyCc: BitcoinLessons; AuthorSubject: Re: [bitcoin-only/bitcoin-only] Content Suggestion: Bitcoin Lessons (#170) 
It sounds like you are positive about some non monetary altcoins. Can you give a example of one you think is not a scam?

**Comment by 6102bitcoin** [comment]
Ok. ACK

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/62868fae37c322a3ee8b076b7668b1b05b880882)
