### ISSUE TITLE
Content Suggestion: Bitplaza Inc.

### ISSUE THREAD

**Issue by alariva** [bitcoin-only/bitcoin-only#175]
1) Link to Content: https://www.bitplazashopping.com/
2) Briefly Describe Content: NEW GEN TECHNOLOGY for Shopping with Bitcoin made easy.
3) Suggested Section: Tools / Stores

**Comment by 6102bitcoin** [comment]
Please can you explain how your service works  - I can'f find this information on the website.

**Comment by alariva** [comment]
@6102bitcoin I'm an external vendor requested to open this issue. Please feel free to [contact the site owners](https://www.bitplazashopping.com/bitplaza/) for the requested info, otherwise feel free to close. Thanks!

**Comment by 6102bitcoin** [comment]
Thanks.
