### ISSUE TITLE
Content Suggestion: IBEX Bitcoin

### ISSUE THREAD

**Issue by rawcdv** [bitcoin-only/bitcoin-only#178]
1) Link to Content: https://www.ibex-bitcoin.com/
2) Briefly Describe Content: We are a Bitcoin Bureau de Change located in London. We buy and sell Bitcoins face-to-face.
3) Suggested Section: Get Bitcoin

**Comment by 6102bitcoin** [comment]
Thanks for raising an issue.

Do you have a premises / where do you typically meet customers?

**Comment by rawcdv** [comment]
We used to meet our clients insude a bank branch.

Because of recent events, we moved to mostly online transactions for now.

**Comment by 6102bitcoin** [comment]
Positive reviews on [paxful](https://paxful.com/user/BuyBitcoinLondon)

If you have any clients who are happy to reply to this tweet please encourage them to do so.

https://twitter.com/BitcoinOnly_/status/1340430656560619523

Thanks

**Comment by 6102bitcoin** [comment]
@rawcdv Is there anyone who can vouch for you?

**Comment by 6102bitcoin** [comment]
No update. Closing issue.
