### ISSUE TITLE
Please add LuxNode

### ISSUE THREAD

**Issue by Amacruz** [bitcoin-only/bitcoin-only#18]
LuxNode is a all-in-one Bitcoin / Lightning Network & Payment Processing Node based on a Intel NUC that runs Bitcoin Core, LND, Ride The Lightning GUI, BTCPayServer, and TOR.

We'd love to get added to your Bitcoin only Hardware section. Luxnode.io

Thanks!

**Comment by 6102bitcoin** [comment]
Thanks for reaching out. It looks interesting but not yet launched.
Will re-evaluate once launched.

**Comment by 6102bitcoin** [comment]
Status: Still Awaiting Launch (As of 2019/10/18)

**Comment by 6102bitcoin** [comment]
Status: Still Awaiting Launch (As of 2020/01/24)

**Comment by pardus79** [comment]
Looks like this project is dead. Website is gone and their twitter appears to just be a bot.

Closing.
