### ISSUE TITLE
Content Suggestion: myNode YouTube video tutorial series

### ISSUE THREAD

**Issue by k3tan172** [bitcoin-only/bitcoin-only#181]
1) Link to Content: https://www.youtube.com/playlist?list=PLCRbH-IWlcW0KP8DxyWWrqahGafZyV2HR
2) Briefly Describe Content: A detailed video series on setting up and using mynodebtc, an avenue for individuals to run a full Bitcoin node.
3) Suggested Section: Hardware > Node: DIY > MyNode - Guide

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/dcb0a9b7ad2442fe25d4fc30dda9a724a024f0c4) Thanks dude
