### ISSUE TITLE
Content Suggestion: Reckless Coffee

### ISSUE THREAD

**Issue by btcpuertorico** [bitcoin-only/bitcoin-only#184]
1) Link to Content: https://reckless.coffee/
2) Briefly Describe Content: Curated selection of premium coffee beans. (P2EP)
3) Suggested Section: spend-bitcoin

**Comment by pardus79** [comment]
Don't know if this site is legit or not, but they do only accept bitcoin and lightning payments.

**Comment by btcpuertorico** [comment]
Hi. This is legitimate. The guy did some IRL sample deliveries to Rodolfo and Mandrik last year. 
https://twitter.com/Mandrik/status/1130889874104627200?s=20
https://twitter.com/nvk/status/1129077878094802945?s=20

**Comment by 6102bitcoin** [comment]
Both products currently have no reviews and are out of stock - Please raise a new issue when you have some reviews / public messages of successful orders & are back in stock. 

I appreciate that this is somewhat of a catch-22 but if you can establish your authenticity it helps with listing.
