### ISSUE TITLE
Content Suggestion: Juggernaut

### ISSUE THREAD

**Issue by johncantrell97** [bitcoin-only/bitcoin-only#185]
1) Link to Content: https://www.getjuggernaut.com/
2) Briefly Describe Content: Send and receive end-to-end encrypted, onion-routed, p2p messages and payments over the lightning network.  Available for windows, mac, and linux desktop.
3) Suggested Section: Hard to know best place, given current options I guess it best fits as a Lightning Wallet but I'd suggest a new section for Lightning Apps? Social? I'm not sure.

**Comment by pardus79** [comment]
Could also go under https://bitcoin-only.com/#privacy

**Comment by 6102bitcoin** [comment]
Yes - looks like a lapps / apps section could be needed.
