### ISSUE TITLE
Content Suggestion: Coinfloor

### ISSUE THREAD

**Issue by obi** [bitcoin-only/bitcoin-only#186]
1) Link to Content: https://coinfloor.co.uk/ (Main site)  and https://coinfloor.co.uk/autobuy (Dollar Cost Averaging / Instant buy service for UK only - EU soon)
2) Briefly Describe Content: The UK and Europe's oldest and biggest Bitcoin Only Exchange.  Automatically buy bitcoins instantly or on a recurring basis (DCA).  Sign up in minutes. 
3) Suggested Section: https://bitcoin-only.com/#get-bitcoin

**Comment by pardus79** [comment]
This exchange used to list ETH. Bitcoin only since January.

https://blog.coinfloor.co.uk/post/189719817726/coinfloor-sets-eyes-on-bitcoin-only-services-from

**Comment by obi** [comment]
Correct.  We listed ETH for less than a year in total and delisted on Bitcoin's 11th anniversary.

https://www.coindesk.com/uks-oldest-crypto-exchange-to-delist-ethereum-and-focus-solely-on-bitcoin 

Back to fully focusing on Bitcoin going forward. :-)

In addition, our retail offering is focused on dollar cost averaging as our main recommended mechanism for new users entering the Bitcoin space.

https://www.coindesk.com/uk-crypto-exchange-coinfloor-launches-no-bs-service-for-bitcoin-beginners

**Comment by 6102bitcoin** [comment]
Thanks for this. A couple of questions:
- Customers at other exchanges have had accounts closed following their use of CoinJoin tools to protect their privacy. What is your position regarding CoinJoin's? 
- I just had a look at your fees and the 'autobuy' fees are 10x the normal fees (2-3.5% vs 0.3%), is this going to remain the case going forwards or is it temporary?

**Comment by 6102bitcoin** [comment]
Having taken a closer look at the other fees charged on the platform (including deposit and withdrawal) the autobuy fees look similar.

**Comment by obi** [comment]
Hi 6102bitcoin,  somehow missed your messages above.  Answers below:

CoinJoins

Our public policy is that all deposits and withdrawals must be first party, whether fiat or bitcoin.  This allows us to more easily meet our regulatory obligations.  So any deposit directly from or withdrawal directly to an address not owned by a user would fail that requirement.

Once in your wallet, you are free to do as you wish with your Bitcoin. However, we do perform blockchain monitoring in line with our interpretation of UK, EU, and upcoming FATF regulations and guidance, and may use the information gleaned as a result to determine if continued trade with a user fits our risk profile. To do otherwise would risk our banking, any regulatory registration, and therefore our continued operation, leaving the UK/EU exchange field wide open to services willing to list multiple altcoins alongside Bitcoin thereby confusing and misdirecting new users towards coins other than Bitcoin.

Fees

With respect to fees, our AutoBuy fees are designed to be competitive with other retail offerings. In fact, for the typical purchase of £20 - £80 we are up to half the price of the biggest UK retail crypto competitor.  The other big difference is that our fees are transparent and simple to understand, versus hard to locate and complex to calculate on certain competitor sites.

Our exchange trading fees are different because it is effectively wholesale pricing.  As you noted, minimum deposits and withdrawals amounts and fees are higher and the overheads of managing a high volume exchange client is lower than a retail client on average.  

As with everything we do, we have attempted to charge fees that are fair but sustainable.

**Comment by obi** [comment]
Thanks guys!
