### ISSUE TITLE
Update Suggestion: "Getting Started" on Get Bitcoin page

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#192]
#191 removes "Bittr in Europe" from "Getting Started" at the top of the page.

What European exchange should take its place?

**Comment by 6102bitcoin** [comment]
Good question Pardus, do you have any suggestion? I am interested in the future to encourage users to use P2P exchanges rather than these kyc services, do you have any thoughts on that?

**Comment by pardus79** [comment]
I don't have any suggestions on European exchanges since I'm not in Europe.

I think non-KYC exchanges are great but are there any that are easy for precoiners to use?

**Comment by obi** [comment]
May I humbly suggestion Coinfloor?

We support UK and European customers on our exchange since launch.  Our DCA (Autobuy) product will soon support EURO DCA as well.

**Comment by 6102bitcoin** [comment]
We actually removed this banner recently so this issue can be closed. Thanks anyway
