### ISSUE TITLE
Update Suggestion: NAME OF CONTENT TO BE UPDATED

### ISSUE THREAD

**Issue by bradyswenson** [bitcoin-only/bitcoin-only#193]
**Please Describe Suggested Update:**
Hi 6102!

Would like to see the description for Swan Bitcoin be updated to "Automatic recurring buys" or "Recurring buys" 

Thanks!
Brady

**Comment by 6102bitcoin** [comment]
I'm trying to keep that page as simple as possible. Might change to have a column for buy and one for sell and a series of check marks / crosses to clean it up. As such, I think adding recurring could be clumsy
