### ISSUE TITLE
Content Suggestion: bitcoinqna.com

### ISSUE THREAD

**Issue by BitcoinQnA** [bitcoin-only/bitcoin-only#195]
1) Link to Content: https://www.bitcoinqna.com/
2) Briefly Describe Content: Simple answers to the most common Bitcoin questions from new users
3) Suggested Section: https://bitcoin-only.com/#learning

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/b4e896652a19fbdca1cfd8e3a1479b208a3c5543)

Thanks!
