### ISSUE TITLE
Add SoCal Lightning Meetup

### ISSUE THREAD

**Issue by abentley8** [bitcoin-only/bitcoin-only#20]
Country: USA
City: Los Angeles
Organiser: @ecurrencyhodler

**Comment by 6102bitcoin** [comment]
https://twitter.com/SoCalLightning/status/1171919340020518912?s=19

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/f143174debe8ab014a39ef5d92d8636a0d83bd8d)
