### ISSUE TITLE
Content Suggestion: A Guide To Understanding Bitcoin (bitcoin-explained)

### ISSUE THREAD

**Issue by bitcoinexplained** [bitcoin-only/bitcoin-only#201]
1) Link to Content: https://www.bitcoin-explained.com
2) Briefly Describe Content: An introduction to the many different reasons of why Bitcoin is so important. Including a curated list of resources for a deeper learning process.
3) Suggested Section: Learning (Websites)

**Comment by 6102bitcoin** [comment]
[Addded](https://github.com/bitcoin-only/bitcoin-only/commit/a4cb2ead5009f2e491db6d938cc9f6a691184c34) Great work
