### ISSUE TITLE
Update Suggestion: Remove RTL

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#207]
RTL is an LND/C-Lightning front-end. LND & C-Lightning both support litecoin and RTL works running when litecoin instead of bitcoin.

RTL has not removed litecoin mentions or functionality from their wallet like Zap has.

**Comment by 6102bitcoin** [comment]
https://github.com/bitcoin-only/bitcoin-only/commit/deb29a9d7d19a6ee35f26b8e05b4aeda9b384459
