### ISSUE TITLE
Content Suggestion: Stekking

### ISSUE THREAD

**Issue by moonshot75** [bitcoin-only/bitcoin-only#212]
1) Link to Content: https://stekking.com
2) Briefly Describe Content: Bitcoin Satsback Rewards via Lightning
3) Suggested Section: GET BITCOIN -> CASHBACK

**Comment by 6102bitcoin** [comment]
Please notify when out of early access

**Comment by moonshot75** [comment]
> Please notify when out of early access

We are now open for everyone, added more than 10K shops today and more to come.

**Comment by moonshot75** [comment]
> Please notify when out of early access

We are out of early access.

**Comment by 6102bitcoin** [comment]
Please encourage your users to provide feedback: https://twitter.com/BitcoinOnly_/status/1340431661247422464

**Comment by AdamTurcoSivas** [comment]
We love stekking!!

**Comment by 6102bitcoin** [comment]
Overwhelmingly positive feedback ACK

**Comment by kkoenen** [comment]
ACK. These guys are breathing btc. Great way to support the lightning protocol.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/0f4e3d21acc230e39179ed77dc962cb15d3dfc4c)
