### ISSUE TITLE
Content Suggestion: LNPay.co

### ISSUE THREAD

**Issue by joe-rodgers** [bitcoin-only/bitcoin-only#214]
1) Link to Content: https://lnpay.co
2) Briefly Describe Content: LNPay is a Lighting Network powered bitcoin-only payments company. 
3) Suggested Section: Store Tools

Notes: LNPay is building out features and services rapidly. It began as fully custodial, however API's are being developed and are very early in development which allow users to connect their own node. 

![Annotation 2020-06-05 161639](https://user-images.githubusercontent.com/25499388/83923472-f9948c00-a747-11ea-8224-13b66db1dc80.png)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/d22b0e5eaff3e4a2c3dc5a64f87ffd6d9d1f32e5)

Great suggestion - Thanks
