### ISSUE TITLE
Content Suggestion: Paybtc

### ISSUE THREAD

**Issue by graysonjlm** [bitcoin-only/bitcoin-only#216]
1) Link to Content: https://paybtc.com.au/
https://twitter.com/paybtc_au

2) Briefly Describe Content: Paybtc is an Australian Bitcoin (only) service that allows people to pay for bills and services using Bitcoin, with the goal of helping Aussies to hold more BTC reserves and exit the banking system.  The Paybtc team has been strictly Bitcoin Only since inception, and has no plans to add other coins. 

3) Suggested Section: Spend Bitcoin

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e429383a53b701c112230581cbb14de5e0ec2b08)

Thanks - Great idea
