### ISSUE TITLE
Hodlinox - Stainless Steel Seedphrase Backup

### ISSUE THREAD

**Issue by hodlinox** [bitcoin-only/bitcoin-only#217]
1) Link to Content: https://hodlinox.com
2) Briefly Describe Content: Stainless steel seed phrase backup for your bitcoin wallet
3) Suggested Section: Spend Bitcoin

**Comment by pardus79** [comment]
First glance, this appears to be bitcoin only. I don't see any mention than it can/should be used for alts and payment is only bitcoin.

LGTM
