### ISSUE TITLE
Content Suggestion: RoninDojo

### ISSUE THREAD

**Issue by BitcoinQnA** [bitcoin-only/bitcoin-only#218]
1) Link to Content: https://code.samourai.io/ronindojo/RoninDojo/-/wikis/home
2) Briefly Describe Content: RoninDojo is an Installation Assistant and UI for Samourai Wallet's Dojo. The goal of RoninDojo is to simplify Dojo on single-board computers. 
3) Suggested Section: https://bitcoin-only.com/#hardware     NODE : DIY

**Comment by pardus79** [comment]
Merged 60954c4
