### ISSUE TITLE
Possible Addition of Cypherpunk Cogitations by Jameson Lopp

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#22]
Just came across this blog by Jameson going over a wide array of interesting information.  Not sure it would fit but definitely want to see.

https://blog.lopp.net/

**Comment by 6102bitcoin** [comment]
Quite a varied amount of content and looking through there were a few non bitcoin-only posts so unfortunately its not suitable for listing.
