### ISSUE TITLE
Content Suggestion: IMPRESS - Retouching Agency

### ISSUE THREAD

**Issue by VolcanoTNT** [bitcoin-only/bitcoin-only#225]
1) Link to Content: https://studio-impress.com/
2) Briefly Describe Content: Freelance photo retouching services
3) Suggested Section: Design

**Comment by 6102bitcoin** [comment]
Unfortunately there is not a design section. 

This would be more suitable to a niche section which I may add in the future - I will close the issue until then.

Thanks
