### ISSUE TITLE
Content Suggestion: More in depth (new to coding/Linux) guide for running your own node

### ISSUE THREAD

**Issue by fhoenyx** [bitcoin-only/bitcoin-only#228]
1) Link to Content: I don't have the content, just a suggestion
2) Briefly Describe Content: the Bitcoin only guide for a simple node setup describes setting up ubuntu with Bitcoin core and wasabi. Bitcoin.org (https://bitcoin.org/en/full-node#other-linux-daemon) describes how to set up the node, but doesn't go much into detail on issues that may come up or why they might happen.
3) Suggested Section: common issues that come up or a simple troubleshooting guide. Or even a "if you're brand spanking new to this...here's your setup. When you're more familiar....here's your setup.

**Comment by pardus79** [comment]
The "Node: DIY" section of https://bitcoin-only.com/#hardware is pretty much this. 

There are guides there for running a node that vary from simply running a setup script to step by step setting up linux and the various apps from command line.

Perhaps some notes indicating which of those are more technical or good for newbies would be beneficial. Or breaking them up by difficulty level.

**Comment by fhoenyx** [comment]
I completely overlooked that section when searching. Thanks! Getting this thing set up now!
