### ISSUE TITLE
Add Original Satoshi

### ISSUE THREAD

**Issue by jstylez13** [bitcoin-only/bitcoin-only#23]
Original Satoshi (https://www.originalsatoshi.com/) is a Bitcoin Store. We sell stickers accepting payment with lightning and also carry other bitcoin related goods from time to time.

**Comment by 6102bitcoin** [comment]
Thanks for the request. Do you have a twitter account?

**Comment by jstylez13** [comment]
Use @originalsatoshi cheers!

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/bb6e8072092fc790f6cbf0f41112fc656e2a2b48)
