### ISSUE TITLE
Content Suggestion: BTC Pins

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#231]
1) Link to Content: www.btcpins.com
2) Briefly Describe Content: Online store selling bitcoin pins.
3) Suggested Section: Spend Bitcoin/Stores

This is my project. Everything is bitcoin. No alts mentioned or accepted for payment.

Brand new, so if you want to tag "waiting" until more established, 👍

**Comment by 6102bitcoin** [comment]
Looks great
