### ISSUE TITLE
Content Suggestion: Research Section

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#233]
Add a research section with links to documents.

**Comment by pardus79** [comment]
Any examples of things you want in this section?

**Comment by wiz** [comment]
This is a great idea, we can start with 6102's coinjoin research and related articles.

**Comment by 6102bitcoin** [comment]
Thanks Wiz. Yes, my research repo would be a good one. Also 
- The recent [report (warning direct link)](https://www.fca.org.uk/publication/research/research-note-cryptoasset-consumer-research-2020.pdf) by the FCA in the uk
- This [paper](https://journals.sagepub.com/doi/abs/10.1177/0263276417746464?journalCode=tcsa&) has been recommended to me directly, although it is paywalled so currently wouldn't be suitable.

**Comment by karozagorus** [comment]
I tried making something as a pull request but then I will just wait.
