### ISSUE TITLE
Content Suggestion: The Social Life of Bitcoin 

### ISSUE THREAD

**Issue by karozagorus** [bitcoin-only/bitcoin-only#235]
1) Link to Content: https://journals.sagepub.com/doi/10.1177/0263276417746464 (will try get you a PDF)
2) Briefly Describe Content: This paper challenges the notion that Bitcoin is ‘trust-free’ money by highlighting the social practices, organizational structures and utopian ambitions that sustain it. At the paper's heart is the paradox that if Bitcoin succeeds in its own terms as an ideology, it will fail in practical terms as a form of money. The main reason for this is that the new currency is premised on the idea of money as a ‘thing’ that must be abstracted from social life in order for it to be protected from manipulation by bank intermediaries and political authorities. The image is of a fully mechanized currency that operates over and above social life. In practice, however, the currency has generated a thriving community around its political ideals, relies on a high degree of social organization in order to be produced, has a discernible social structure, and is characterized by asymmetries of wealth and power that are not dissimilar from the mainstream financial system. Unwittingly, then, Bitcoin serves as a powerful demonstration of the relational character of money.
3) Suggested Section: Research within Learning

**Comment by karozagorus** [comment]
I should be possible to message the authors. The paywalls are not really paywalls, researchers always provide academic papers free of charge to others.

**Comment by 6102bitcoin** [comment]
Any luck?

**Comment by 6102bitcoin** [comment]
Closing.
