### ISSUE TITLE
Content Suggestion: https://live-bitcoin-price.com/

### ISSUE THREAD

**Issue by thunderbiscuit** [bitcoin-only/bitcoin-only#248]
1) Link to Content: 
[live-bitcoin-price](https://live-bitcoin-price.com/)

2) Briefly Describe Content:
The project is trying to be the simplest bitcoin price ticker on the internet. I initially built it for someone who was looking to have his Raspberry Pi screen display a simple bitcoin price, sort of as a cool decorative piece (instead of the usual Raspiblitz more technical details about the node and all). Anyway I liked the simplicity of just pinging a website and it returning a straight number. No graph, no other info. Just a straight price ticker.

The ticker is updated every 5 seconds by pinging the Kraken API and asking for the price on the latest BTC/USD trade.

I have registered a domain for it (https://live-bitcoin-price.com/) if you want to use it that way, but I also maintain a single page version of it in [a repo here](https://github.com/thunderBiscuit/live-btc-price) so people can download and just double-click to open in their browser directly. This allows for having it locally on desktop or smartphone and not have to ping my website at all.

3) Suggested Section:
Not sure about this one. Probably the dev tools.

**Comment by wiz** [comment]
Cool site, I like how it's direct and straight to the point with no BS. However, it might be too minimalistic for a portal site like Bitcoin Only, typically there is more rich content. Maybe if we had some kind of price tickers resource section it would work, but I'm not sure this fits into the theme of the site right now.

**Comment by thunderbiscuit** [comment]
Yeah good point. I can see how it doesn't quite fit anywhere in particular.

I guess the value is more in the single html file which you could reuse and modify if you need a price ticker somewhere (example above was for a small Pi with a screen), but again that's a rather super small and oddball use case haha.

**Comment by 6102bitcoin** [comment]
It's a nice idea.

Agree with Wiz that there isn't a place to put it with it's own row. That said, it is similar to cent2sat so I have [added](https://github.com/bitcoin-only/bitcoin-only/commit/b3d4cc9bb53eb9fe05d6af8730b61526cdaeaaa6) it there.

**Comment by thunderbiscuit** [comment]
Nice! 

Cheers, guys. Love the site, and I always refer people to it!
