### ISSUE TITLE
Content Suggestion: Konsensus Network - The Bitcoin Publishing House

### ISSUE THREAD

**Issue by omnifinn** [bitcoin-only/bitcoin-only#249]
1) Link to Content: https://konsensus.network/
2) Briefly Describe Content: Translated and localized Bitcoin books
3) Suggested Section: Spend bitcoin/stores
![konsensus-publishing-house-e1590424345615](https://user-images.githubusercontent.com/58121410/88478518-aeca1000-cf51-11ea-8ca9-977d014222fd.png)

**Comment by wiz** [comment]
ACK - please proceed with PR

**Comment by pardus79** [comment]
#251
