### ISSUE TITLE
Update Suggestion: Moneybadger Shop

### ISSUE THREAD

**Issue by omnifinn** [bitcoin-only/bitcoin-only#250]
**Please Describe Suggested Update:**
I am the maintainer of the moneybadger.shop and due to non-existent sales, the shop goes dormant until further notice. We might come back up later but as of now, it would be better to remove it from your site. Thank you!

**Comment by wiz** [comment]
Okay but the shop still appears to be online and taking orders, are you sure you want to remove it right now?

**Comment by omnifinn** [comment]
Yeah, I’m sure. The last order was about a year ago. I need to reboot the concept and I don’t have the time right now. Focusing on Konsensus Network that provides a more valuable service and has regular sales.

**Comment by pardus79** [comment]
#251
