### ISSUE TITLE
Meetup Suggestion: Bitcoin Enemies

### ISSUE THREAD

**Issue by joe-rodgers** [bitcoin-only/bitcoin-only#256]
## Required:
1. Name of Meetup: Bitcoin Enemies
2.  Location Of Meetup: Cyberspace
3. At least one of the following:
- Website: [https://bitcoinenemies.com/](https://bitcoinenemies.com/)

## Optional 
- Name of Organiser(s) & Twitter Handle: [Bitcoin Enemies on Twitter](https://twitter.com/bitcoinenemies) & [Mosats the organizer on Twitter](https://twitter.com/satwhale)
- Links showing public support: >>>  [I retweeted this](https://twitter.com/biTcOinEneMiEs/status/1285608389607817225)
- Tweet your commitment: [This is a 24/7 Chat room and meetup space for Bitcoiners.](https://twitter.com/_joerodgers/status/1288130579075145729)

```
As a moderator of [Bitcoin Enemies] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by wiz** [comment]
Hmm, I think we may be stretching the definition of "meetup" quite a bit. AFAIK the term "meetup" typically refers to a physical IRL meetup group on meetup.com - perhaps we should make a separate section on the website for chat rooms

**Comment by pardus79** [comment]
There is a "Cyberspace" country under meetups for Udi's VR meetups. Could use that.

But yeah, it doesn't really fit the "meetup" label since it's more like a telegram/slack chat or bitcoin twitter.

**Comment by wiz** [comment]
Yeah, maybe we can make a "community" section for this and Udi and hive.one etc.?

**Comment by pardus79** [comment]
Unless there are a lot of items we would list in Community to require its own page, I would just add a subsection to the Meetup page.

**Comment by wiz** [comment]
That's a good point, we can just have virtual meetups in their own section at the bottom. Since it was your idea, did you want to make PR? 😅

**Comment by 6102bitcoin** [comment]
I like the idea of having the cyberspace meetups at the top (as per the bitcoinVR meetup) because they are applicable to everyone & everyone starts at the top before scrolling to their location.

**Comment by pardus79** [comment]
ACK

**Comment by satwhale** [comment]
Hey guys,

Thanks Joe and Bitcoin_Only team for your consideration. Appreciate the work you're all doing. Sorry for coming in cold, should have made more of an introduction.

I've included some more information below. Also, while we are a 24/7 server, we do have organized bi-weekly events and intend to make the server a popular Bitcoin meetup destination.   

> ## Required:
> 
>     1. Name of Meetup: Bitcoin Enemies
> 
>     2. Location Of Meetup: Cyberspace
> 
>     3. At least one of the following:
> 
> 
>     * Website: https://bitcoinenemies.com/
> 
> 
> ## Optional
> 
>     * Name of Organiser(s) & Twitter Handle: [Bitcoin Enemies on Twitter](https://twitter.com/bitcoinenemies) & [Mosats the organizer on Twitter](https://twitter.com/satwhale)
If possible, please use Bitcoin Enemies twitter as the organizer. There are multiple organizers and they will all be covered by this account.

> 
>     * Links showing public support: >>>  [I retweeted this](https://twitter.com/biTcOinEneMiEs/status/1285608389607817225)
>
Here's a few more

https://twitter.com/DiverterNoKYC/status/1286450502989942784?s=20
https://twitter.com/bergealex4/status/1272717910495150080?s=20
https://twitter.com/Bas_02/status/1271485476810231813?s=20
https://twitter.com/SamouraiDev/status/1271399674616954880?s=20
https://twitter.com/poorbengunn/status/1271164755152195585?s=20
https://twitter.com/hodlonaut/status/1271046482293067776?s=20
https://twitter.com/christinabahk/status/1273696060586647552?s=20
https://twitter.com/maxtannahill/status/1268537512429060102?s=20
https://twitter.com/lightcoin/status/1286365937743155202?s=20
https://twitter.com/BITPAINTclub/status/1286985842175758338?s=20

>     * Tweet your commitment: [This is a 24/7 Chat room and meetup space for Bitcoiners.](https://twitter.com/_joerodgers/status/1288130579075145729)
> 
> 
> ```
> As a moderator of [Bitcoin Enemies] Meetup I can confirm that the meetup is bitcoin-only
> -The meetup is bitcoin focused.
> -'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
Also, our members wouldn't stand for anything less.
 
> #bitcoinonlymeetups @bitcoinonly_
> ```
