### ISSUE TITLE
Content Suggestion: Hexawallet

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-only/bitcoin-only#257]
1) Link to Content: https://hexawallet.io
2) Briefly Describe Content: Add Bitcoin only Hexa wallet to the wallets section. non-custodial, no shitcoins, open source, multisig option, user friendly. 
3) Suggested Section: Wallets section

**Comment by modl21** [comment]
ACK

I am working with them. Ambitious team. Non-custodial bitcoin wallet for android and iOS.

**Comment by wiz** [comment]
Okay cool, proceed with PR

**Comment by Varunram** [comment]
Varunram from the hexa team here. Thanks to all for the approval, will submit a PR later today.

**Comment by 6102bitcoin** [comment]
It's been added
