### ISSUE TITLE
Content Suggestion: Bitcoin Rehab Podcast

### ISSUE THREAD

**Issue by karozagorus** [bitcoin-only/bitcoin-only#262]
1) Link to Content: https://anchor.fm/bitcoinrehab
2) Briefly Describe Content: Bitcoin fireside chat, with bitcoiners, about bitcoin related topics or life experiences. Interviewing and chatting with mostly bitcoin plebs or individuals who are mostly hidden away in the crowd.
3) Suggested Section: Link to the podcast page.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/d8aeca522ca64ab56f99a40f18761764d82899a6)
