### ISSUE TITLE
Content Suggestion: #NotiSatoshi (a Bitcoin-Only news recap in spanish)

### ISSUE THREAD

**Issue by criptobastardo** [bitcoin-only/bitcoin-only#265]
1) Link to Content: https://www.youtube.com/watch?v=ZqGJdIfrJGc&list=PLZsflIub4SmESRXVrl1AkXUcu96ahF5c1
2) Briefly Describe Content: #NotiSatoshi is a Bitcoin only weekly recap of the main news in Bitcoin.
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Messaged @satoshienvzla on twitter who's name is shown in the video.

**Comment by pardus79** [comment]
Pretty sure @satoshienvzla is @criptobastardo

**Comment by criptobastardo** [comment]
Yes, i'm @satoshienvzla @ Twitter too.

I do use both accounts untill we grow big enough to have Community Managers
lol

Cheers!

Thanks for the adding, pals! REALLY appreciated

J-

**Comment by 6102bitcoin** [comment]
Ready to be turned into a Pull Request.

**Comment by pardus79** [comment]
Was about to add this, but noticed that this show is on the same youtube channel as https://www.youtube.com/c/SatoshienVenezuela/ which is already listed.

Should this replace the existing listing?

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e6e6c360d70b1a4764edbd5aad449b8887f4e11d)
