### ISSUE TITLE
Content Suggestion: estudiobitcoin.com (a great spanish source of sources)

### ISSUE THREAD

**Issue by criptobastardo** [bitcoin-only/bitcoin-only#266]
1) Link to Content: https://estudiobitcoin.com/
2) Briefly Describe Content: This site, built by Lunaticoin and Arkad, is one of the most prominent places where spanish speakers can find resoursers to DYOR on Bitcoin
3) Suggested Section: Learning / Periodicals

**Comment by pardus79** [comment]
LGTM (with some translation help)

Section should be Learning / Websites instead of Periodicals

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/b143f503a2c009d0001ff687aa289979850d3f65)
