### ISSUE TITLE
Content Suggestion: Phoenix Wallet

### ISSUE THREAD

**Issue by ndalliard** [bitcoin-only/bitcoin-only#268]
1) Link to Content: https://phoenix.acinq.co/
2) Briefly Describe Content: Lightning Wallet from ACINQ
3) Suggested Section: Wallets -> Lightning

Any reasons why this is not already listed?

**Comment by pardus79** [comment]
I couldn't find any prior issues regarding this wallet. I think it was just never suggested.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/3f9aa4c2eb9e7dd86f7201743bbcc4e25da88da0)

**Comment by ndalliard** [comment]
Not sure if «lightning-only» is fitting. You can pay to normal bitcoin addresses and also receive from the first layer. Called Swap-in and Swap-out. See the [FAQ](https://phoenix.acinq.co/faq#what-are-the-fees) for more informations. Sure, it probably shouldn't be used as a normal bitcoin wallet. Just my 2 sats.
