### ISSUE TITLE
Update Suggestion: Alphabetization Consistency

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#271]
I'm going to review the lists on each page since there are some inconsistencies with the alphabetization. IMO, items that start with "The" should be listed based on the first letter of the following word. 

Example: "The Chaincode Podcast" is in the list as starting with "C". "The Bitcoin Basics Podcast" is under "T"

Which method should be used on the site, so I can make things consistent?

**Comment by wiz** [comment]
What if we just remove "The" so it fits better?

**Comment by pardus79** [comment]
It would fit better, but I prefer to keep the name that the podcaster/author created for their work. We shouldn't change the name of "The Bitcoin Standard" to "Bitcoin Standard". It wouldn't be the correct name".

**Comment by wiz** [comment]
Funny, that's exactly what we did for the Japanese version of the book, but I see your point :)
But in that case, I guess the "The" should be considered in the alphabetization since you consider it part of the title?

**Comment by pardus79** [comment]
That works, either is correct really. It should just be consistent.

I'll keep "The"s and put them as "T"
