### ISSUE TITLE
Content Suggestion: Einundzwanzig Podcast

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#278]
1) Link to Content: https://anchor.fm/einundzwanzig
2) Briefly Describe Content: Bitcoin-only podcast in German
3) Suggested Section: Podcasts

**Comment by pardus79** [comment]
Translated website and it all appears bitcoin only. Also, it is Gigi's pod.

**Comment by 6102bitcoin** [comment]
ACK
