### ISSUE TITLE
Feature Suggestion: Foreign language section

### ISSUE THREAD

**Issue by AbelLykens** [bitcoin-only/bitcoin-only#289]
Because of #285 , adding a separate request for foreign language. I think this could be a good idea.

Challenge would be: how to verify it's really bitcoin only.

**Comment by 6102bitcoin** [comment]
ACK.

Would request that submissions;
- Include links to attestations (tweets) in English confirming that the content is bitcoin-only from listeners  

And / Or

- Are accompanied by comments in the pull request / issue from listeners who can attest to the podcast being bitcoin-only.

**Comment by pardus79** [comment]
See #287

**Comment by 6102bitcoin** [comment]
Looks like this has been dealt with. Cheers
