### ISSUE TITLE
Update Suggestion: Remove Blockstream Green

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#290]
Blockstream Green Wallet has support for Liquid [Issued Assets](https://blockstream.info/liquid/assets) which include many 'synthetic' shitcoins or shitcoin IOU's, for example [Liquid Ethereum](https://blockstream.info/liquid/asset/0720f3ad7cc0e2afe0c0c26c382220ffa644a77f03ce5450a01909d0fd892155 ). 

For this reason I propose removing it from the Wallets page.

**Comment by pardus79** [comment]
ACK
