### ISSUE TITLE
List Lapps.co

### ISSUE THREAD

**Issue by ruigomeseu** [bitcoin-only/bitcoin-only#3]
Hey!

Was wondering if you could list [Lapps](https://www.lapps.co) in your platform.

It's a platform that lists apps using the Lightning Network (on bitcoin of course :) ).

**Comment by 6102bitcoin** [comment]
Hey!

Nice site. After having a look I quickly found a listed app which supports altcoins ("Coincards is the premium platform for living off Bitcoin **and Altcoins**").

If you are planning on listing only bitcoin-only apps then please let me know when you have updated your app list and I'll check it out.

If not, I'll check through the apps and add any missing bitcoin-only apps to bitcoin-only.com
