### ISSUE TITLE
Update Azteco Info

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#30]
Azteco is now live in London. 

https://medium.com/@Azteco_/an-espresso-panini-and-a-bitcoin-please-d9a05aad2c6c

**Comment by PuraVlda** [comment]
Looks like it is live in multiple places, may be tough to list as a single location.  Thoughts?
<img width="895" alt="Screen Shot 2019-09-15 at 6 51 47 PM" src="https://user-images.githubusercontent.com/51298667/64928701-79ba4080-d80b-11e9-9716-7a28d41f9c80.png">

**Comment by PuraVlda** [comment]
Made Pull Request to change location to Worldwide.

**Comment by 6102bitcoin** [comment]
Thanks! [Merged](https://github.com/bitcoin-only/bitcoin-only/pull/36)
