### ISSUE TITLE
Update Suggestion: Split out new wallets in wallet list 

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#302]
**Please Describe Suggested Update:**

The new wallets should be put somewhere seperate to the older, more stable wallets.

**Comment by pardus79** [comment]
The wallet page already has a lot of subsections.

Would it be ok to put new wallets at the bottom of their subsection and just put "(NEW)" next to their name? We could add a disclaimer that we recommend users generally avoid new software due to potential bugs.

**Comment by 6102bitcoin** [comment]
Would like to revisit this. @pardus79 & @wiz  Do you have any thoughts on how best to present the wallets while we are doing a reformatting? Should we have a recommended wallet for each platform?

**Comment by 6102bitcoin** [comment]
I've been thinking about this some more, I think we could have 
- a popular wallets section at the top with a wallet for each platform, covering both bitcoin onchain & lightning 
- a section for other onchain wallets
- a section for other lightning wallets 

Then the question is what to do with;
- closed source wallets (nunchuk & casa) 
- custodial accounts (currently described as custodal 'wallets')

My preference would be
- Have the closed source wallets in a seperate section at the bottom of the page
- Remove the custodial accounts from this page all together, or at very least add some more detail about the risks of using custodial accounts rather than wallets.

**Comment by pardus79** [comment]
I think custodial wallets should be listed with a disclaimer or in their own subsection. Some vastly improve the UX for newcoiners and have some useful features for advanced users. For example, Wallet of Satoshi makes it really easy to move funds from lightning to on-chain without closing channels.

As far as what to call them, "Accounts" may make it more confusing to readers. "Custodial Apps/Services" may be clearer.

**Comment by 6102bitcoin** [comment]
Ok, Regarding Custodial Services do you think they belong on the wallets page?

**Comment by pardus79** [comment]
If it is meant to function like a wallet (confirming/signing transactions) then yes. But a separate section at the bottom with disclaimer would be appropriate.

**Comment by wiz** [comment]
Your proposal sounds great, but I would suggest not listing custodian services at all, as this isn't Bitcoin but a Bitcoin IOU service

**Comment by pardus79** [comment]
There are some people who will want to hold their bitcoin with a custodian. There are some people that simply cannot hold their own bitcoin.

So would it be better to not list any custodial solutions and leave them to find what they need on google, likely to find a crappy one and lose their money? Or would it be better to list some on bitcoin-only with some education about the trade-offs, getting them started on the road to self-custody?

**Comment by 6102bitcoin** [comment]
For now I have moved the closed source apps into their own section, added a suggestion of blue wallet for iOS users, suggested people on desktop use specter with core and re-ordered the notes at the bottom of the page. 

If people have specific suggestions for changes please open a new issue.
