### ISSUE TITLE
Meetup Suggestion: **De Bitcoin Meetup**

### ISSUE THREAD

**Issue by JWBurgers** [bitcoin-only/bitcoin-only#317]
## Required:
1. De Bitcoin Meetup 
2.  Amsterdam Netherlands 
3. At least one of the following:
- Meetup page: https://www.meetup.com/De-Bitcoin-Meetup/ 
- Website: https://debitcoinshow.nl/

## Optional 
- Boris van de Ven (@GKBoris), Aaron van Wirdum (@AaronvanW), Jan-Willem Burgers (@JWBurgers)

```
As the organiser of De Bitcoin Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/801a9bef260babb02a0e4d4b757203be19a8d156) 

Thank you.
