### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by JWBurgers** [bitcoin-only/bitcoin-only#318]
## Required:
1. De Bitcoin Meetup 
2.  Amsterdam Netherlands 
3. At least one of the following:
- Meetup page: https://www.meetup.com/De-Bitcoin-Meetup/ 
- Website: https://debitcoinshow.nl/

## Optional 
- Boris van de Ven (@GKBoris), Aaron van Wirdum (@AaronvanW), Jan-Willem Burgers (@JWBurgers)

**Comment by pardus79** [comment]
Duplicate #317
