### ISSUE TITLE
Content Suggestion: BTCPay Server

### ISSUE THREAD

**Issue by l33d4n** [bitcoin-only/bitcoin-only#319]
1) Link to Content: https://btcpayserver.org/
2) Briefly Describe Content: Open Source Payment Processor for Bitcoin
3) Suggested Section: STORE TOOLS

**Comment by pardus79** [comment]
See #5

**Comment by l33d4n** [comment]
> **BTCPay Server now has two separate builds.**
> 
> The **Bitcoin only build** and the Altcoin build. **The Bitcoin build is the new default and excludes every bit of code related to altcoins from the source code**.

https://blog.btcpayserver.org/btcpay-server-1-0-5-4/

Altcoins are maintained by their communities and aren't even mentioned on the official BTCPay Server site.

**Comment by pardus79** [comment]
Appears to be on their official site.
https://docs.btcpayserver.org/Altcoins/
https://docs.btcpayserver.org/FAQ/FAQ-Altcoin/

**Comment by l33d4n** [comment]
Without being petty but this is the documentation, not the [official website](https://btcpayserver.org/).

- The official website includes information about Bitcoin only.
- The documentation includes information about third-party extensions developed by the community.

> **Bitcoin is the only focus of the project and its core developers.** However, opt-in integrations are available for several altcoins
> ...
> **Altcoins are maintained by their respective communities.**

https://docs.btcpayserver.org/Altcoins/

BTCPay Server is the most popular and simple solution, the core developers and a large community of contributions working on accessibility of Bitcoin and the Lightning Network.

Because of two pages of documentation that include information about third-party extensions developed by the community, you should miss this project? Is it worth it?
