### ISSUE TITLE
Content Suggestion: SPHINX.CHAT

### ISSUE THREAD

**Issue by klauslovgreen** [bitcoin-only/bitcoin-only#321]
1) Link to Content: https://sphinx.chat
2) Briefly Describe Content: Secure chat, wallet and groups over Lightning
3) Suggested Section: COMMUNICATION TOOLS

**Comment by 6102bitcoin** [comment]
Currently 0 Availability on the website https://sphinx.chat/

**Comment by klauslovgreen** [comment]
Yes - nodes are being bought as quickly as they are added. Nodl is managing
the nodes for now.

--

*Klaus Lovgreen*

(+33) 680 865 167
www.evershift.com

**Comment by pardus79** [comment]
I've used this and it is bitcoin-only. They also have software for running Sphinx with your own lightning node, so you don't have to pay for a server with them.

**Comment by 6102bitcoin** [comment]
Agreed - This is a great tool.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/734382a02411572879b53d8534c7a22f15954c75)
