### ISSUE TITLE
Content Suggestion: bitcoinprivacy.guide by bitcoin q&a

### ISSUE THREAD

**Issue by modl21** [bitcoin-only/bitcoin-only#322]
1) Link to Content: https://bitcoinprivacy.guide/
2) Briefly Describe Content: bitcoin privacy guide by bitcoin q&a
3) Suggested Section: https://bitcoin-only.com/#privacy

**Comment by pardus79** [comment]
Solid guide. They list altcoin exchanges on the "[Sourcing Your Bitcoin](https://bitcoinprivacy.guide/get.html)" page though.
