### ISSUE TITLE
Content Suggestion: River Learn

### ISSUE THREAD

**Issue by SachinMeier** [bitcoin-only/bitcoin-only#326]
1) Link to Content: https://River.com/learn/
2) Briefly Describe Content: A place to learn about Bitcoin basics, investing, and technicals. River Learn includes a glossary of 120 Bitcoin-related terms.
3) Suggested Section: Learning or Bitcoin?

**Comment by wiz** [comment]
ACK - River is definitely Bitcoin Only and they are already listed under the "Buy Bitcoin" section, but this new "Learn" content can go under Learning
