### ISSUE TITLE
Meetup Suggestion: **Taiwan Bitcoin-only Meetup**

### ISSUE THREAD

**Issue by thebtcgirl** [bitcoin-only/bitcoin-only#329]
## Required:
1. Name of Meetup: Taiwan Bitcoin-only Meetup
2.  Location Of Meetup: Taiwan
3. At least one of the following:
- Meetup Page (or similar): www.meetup.com/Taiwan-Bitcoin-Only-Meetup/ 

## Optional 
- Name of Organiser(s) & Twitter Handle: @BTCwisdom4bp
- Links showing public support: https://twitter.com/BTCwisdom4bp/status/1322065039658950656
- Tweet your commitment 

```
As the organiser of #Taiwan Bitcoin-only Meetup, I can confirm that the meetup is #Bitcoin focused. We focus on the tech, not speculation and trading. 'Altcoins' are not supported and promoted. Join the community now: https://bit.ly/31QSxKv #bitcoinonlymeetups 
@BitcoinOnly_

```

**Comment by wiz** [comment]
ACK

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/2a14e3835c8e91df64229078d5e1feb4d23f0b9b)
