### ISSUE TITLE
Caught Wind Joule added support for Decred

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#33]
Catching wind Joule added support for Decred.  Can someone else verify?  We may need to adjust the site accordingly.

**Comment by PuraVlda** [comment]
https://github.com/joule-labs/joule-extension/pull/230

**Comment by 6102bitcoin** [comment]
Good spot! Thanks. Will merge a pull request removing joule when one is available or when I am back at keyboard (few days)

**Comment by PuraVlda** [comment]
Pull request made.

**Comment by 6102bitcoin** [comment]
Removed https://github.com/bitcoin-only/bitcoin-only/pull/35
