### ISSUE TITLE
Meetup Suggestion: **Chiang Mai, Thailand**

### ISSUE THREAD

**Issue by nolim1t** [bitcoin-only/bitcoin-only#337]
## 1. Name of Meetup: 
Chiang Mai Bitcoin Only Meetup

2.  Location Of Meetup: 
Chiang Mai Thailand

3. At least one of the following:
https://t.me/cmbtcevents

## Optional 
- Name of Organiser(s) & Twitter Handle: 
[@nolim1t](https://twitter.com/nolim1t) on twitter

- Links showing public support 
Telegram announcement channel has already 30ish subscribers. Meetups already have 8-10 people (not bad for closed borders)
-  Tweet your commitment
https://twitter.com/nolim1t/status/1324629315972001793

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/88e585a040004f9e5b6fc69322612a14094d1ef6)

Thank you!
