### ISSUE TITLE
Content Suggestion: dcaTracker

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#343]
1) Link to Content: https://dcatracker.com/
2) Briefly Describe Content: track DCA methods
3) Suggested Section: get-bitcoin

**Comment by pardus79** [comment]
NACK

One of the listed exchanges supports buying alts.

https://support.coincorner.com/hc/en-us/articles/360002165173-What-coins-can-I-buy-
