### ISSUE TITLE
Hodl Hodl Lending Supports Altcoins

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#344]
https://lend.hodlhodl.com/

They are supporting lending against bitcoin holdings using etherium-based stablecoins PAX & DAI.

Should this effect their listing on bitcoin-only?

Should podcasts advertising this product be effected as well? Stephan Livera read an ad for this on his newest episode and mentioned these altcoins as part of the service in the ad.

**Comment by 6102bitcoin** [comment]
We won't list it in that case. I'll check out the SLP episode

**Comment by wiz** [comment]
IMO a simple fiat coin like Tether USD isn't an "altcoin" since it's just a fiat IOU, but the PAX and DAI coins might be harder to classify as such, especially if they require ETH to use them. @6102bitcoin maybe it's time we try to define what exactly makes an altcoin an altcoin :)

**Comment by 6102bitcoin** [comment]
Dai, Pax & USDC all run on an altcoin network. 

Tether runs on an altcoin network, and also on liquid.

Only Tether on Liquid is acceptable (because liquid isn't an altcoin).

**Comment by wiz** [comment]
Yeah, agree on all those points, guess we have no choice but to delist if they "support altcoins" which includes PAX and DAI

**Comment by 6102bitcoin** [comment]
[Removed](https://github.com/bitcoin-only/bitcoin-only/commit/4fbc7b35d86753984b4d671010a03eb384b1c450)

The next question is whether SLP is unsuitable for listing. I guess so, but it's a significant loss. Even if SLP were to cut out all mention of the altcoin stablecoins it would still be driving people to a non bitcoin-only site.

**Comment by pardus79** [comment]
If you delist (think you should, for consistency), is SLP forever "tainted"
as long as the eps with that sponsor exist online? Or if there is a change
back to bitcoin-only sponsors, can they be re-listed? Maybe after x
eps/weeks?

**Comment by wiz** [comment]
But SLP is not directly shilling altcoins, he just has one sponsor that happens to support a few altcoins - that's not the same thing

**Comment by pardus79** [comment]
BTC Sessions was rejected from being listed because one of their sponsors was a hardware wallet that supported altcoins though the host pointed out that the wallet had bitcoin-only firmware and they recommend people use it.

We should be consistent.

**Comment by wiz** [comment]
That sounds very unreasonable. From your description, BTC Session was not "supporting altcoins"

**Comment by pardus79** [comment]
BTC Sessions was not shilling altcoins, they advertised a product that had altcoins support but they recommended using the bitcoin-only firmware. @6102bitcoin determined this disqualified them from listing.

By that standard, SLP should be de-listed. I think even more so because his ad mentions altcoin support and doesn't recommend against using the altcoins like Sessions does.

**Comment by 6102bitcoin** [comment]
[Here is a link](https://github.com/bitcoin-only/bitcoin-only/pull/307#issuecomment-694458909) to the BTCsessions listing discussion.

The fundamental disagreement here is whether being sponsored by a company / service that is intelligible for listing makes you inelligible.

**Comment by pardus79** [comment]
No disagreement on my end regarding that. It's ultimately your website and it's up to you to set the standard for what is listed. 

I appreciate the principled approach to what gets listed here and what doesn't, and a big part of that is applying your standards consistently and not playing favorites. 

There are good reasons for not listing them. There are good reasons why they should be listed. Either way you go, they should be both listed, or both not listed.
