### ISSUE TITLE
Meetup Suggestion: **Bitcoin Pakistan Meetup**

### ISSUE THREAD

**Issue by hx4bc** [bitcoin-only/bitcoin-only#346]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoin Pakistan 
2.  Location Of Meetup: Pakistan
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/bitcoin-pakistan
- Telegram Group (or similar): 
- Website: https://bitcoinpk.org

## Optional 
- Name of Organiser(s) & Twitter Handle: @FarooqAhmedE
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Thanks

[Added](https://github.com/bitcoin-only/bitcoin-only/compare/09d309e984d3...e94446f4af3c)
