### ISSUE TITLE
Content Suggestion: SatoshiVPN

### ISSUE THREAD

**Issue by jmarbach** [bitcoin-only/bitcoin-only#347]
1) Link to Content: https://satoshivpn.com
2) Briefly Describe Content: Private and anonymous VPN servers.
3) Suggested Section: Spend Bitcoin > Tools

**Comment by 6102bitcoin** [comment]
Looks interesting. Initial reaction
- $1 / day seems expensive
- No track record & Anonymous operators make me suspicious. 

Could add but with a note saying to be wary. Thoughts @wiz ?

**Comment by wiz** [comment]
My concern is that any "Bitcoin VPN" software could be malicious, if it's not open source or widely used I'm not sure we should direct users to download untrusted software. And yes $1/day is quite expensive, most popular VPNs are $4/month and also take Bitcoin.

**Comment by 6102bitcoin** [comment]
Agreed. Sorry @jmarbach but for now it's a NACK.
