### ISSUE TITLE
Meetup Suggestion: **Bitcoin Saigon Meetup**

### ISSUE THREAD

**Issue by BTCxEagle** [bitcoin-only/bitcoin-only#348]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoin Saigon
2.  Location Of Meetup: Saigon (Ho Chi Minh City) - Vietnam
3. At least one of the following:
- Meetup Page (or similar): www.twitter.com/BitcoinSaigon
- Telegram Group (or similar): https://t.me/BitcoinSaigon_public
- Website: www.bitcoinsaigon.org

## Optional 
- Name of Organiser(s) & Twitter Handle: www.twitter.com/BitcoinSaigon
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by wiz** [comment]
ACK - I've attended this meetup a few timesand it's legit
