### ISSUE TITLE
Content Suggestion: Get Coined

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#349]
1) Link to Content: https://www.getcoined.io/
2) Briefly Describe Content: Education for pre-coiners
3) Suggested Section: Learning>Websites

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/534c0b7ed7d9f3cc05cea771f5b13f68e69dd7fc)
