### ISSUE TITLE
Content Suggestion: NAME OF CONTENT TO BE ADDED

### ISSUE THREAD

**Issue by Evolution-Host** [bitcoin-only/bitcoin-only#350]
1) Link to Content: https://evolution-host.com/bitcoin-vps.php
2) Briefly Describe Content: A VPS you can buy with Bitcoin. Crypto friendly hosting provider
3) Suggested Section: Tools

**Comment by pardus79** [comment]
This site accepts payment in altcoins and offers some altcoin-based services (https://evolution-host.com/ethereum-vps.php).
