### ISSUE TITLE
Content Suggestion: Store - artdesignbysf.com

### ISSUE THREAD

**Issue by artdesignbySF** [bitcoin-only/bitcoin-only#351]
1) Link to Content: https://artdesignbysf.com/
2) Briefly Describe Content: Custom art and graphic design. Think animated logo's, illustrations and custom BTCPay CSS design.
3) Suggested Section: Spend Bitcoin > Stores (or Services maybe)

(Thank you!)

**Comment by 6102bitcoin** [comment]
Added
