### ISSUE TITLE
Content Suggestion: xsats

### ISSUE THREAD

**Issue by xsats** [bitcoin-only/bitcoin-only#354]
1) Link to Content: iOS: https://apps.apple.com/gb/app/xsats/id1525551447 , Android: https://play.google.com/store/apps/details?id=com.xsats.xsats
2) Briefly Describe Content: The xsats mobile app allows bitcoiners and newcoiners to seamlessly and cost-effectively buy bitcoin directly to self-custody. Non-custodial. 100% Bitcoin. £ support with € on the way
3) Suggested Section: Get Bitcoin

**Comment by pardus79** [comment]
Recommend @6102bitcoin request reviews of this service on Twitter before adding, as they are brand new.

**Comment by 6102bitcoin** [comment]
Agreed. They were under consideration some time ago and reviews were positive but limited in number. They have since developed apps & added KYC. I have [tweeted](https://twitter.com/BitcoinOnly_/status/1339703685216161793?s=20), we will review again in 1 month from 2021/01/17. @xsats please remind me if I have not taken action by 2021/02/01.

**Comment by xsats** [comment]
> Recommend @6102bitcoin request reviews of this service on Twitter before adding, as they are brand new.

Thanks for your consideration. Just wanted to note that we're not brand new - have been serving our happy clients since Sept 2019

**Comment by 6102bitcoin** [comment]
You had significant downtime since then no? @xsats

**Comment by xsats** [comment]
> You had significant downtime since then no? @xsats 

There was a period at the beginning of this year where we were unbanked, but we now have stable backing relationships and have offered continual services since spring.

**Comment by 6102bitcoin** [comment]
Ack

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/ef7dab69f10f43fa279b22fa58f5ee53ab0a9dba)
