### ISSUE TITLE
Add Nunchuk to list of wallets

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-only/bitcoin-only#355]
Nunchuk is a relatively new Bitcoin only wallet coordinator, much like Specter.

https://nunchuk.io/

**Comment by 6102bitcoin** [comment]
It appears that only the library is OpenSource, but not the front end. This seems like a security concern.

**Comment by 6102bitcoin** [comment]
Messaged dev's for clarification

**Comment by 6102bitcoin** [comment]
Front end is closed source. Currently a malicious front end  could present non user-derived addresses, leading to loss of funds. Work is ongoing to resolve this so I will review once these mitigations are made.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/compare/bcbb11b91eae...c96edb01be3e) to the closed source section. 

I appreciate that being open source does not necessarily mean a wallet is more secure (especially if not reproducible) but I think the assumption is that wallets are open, therefore the distinction is important.

**Comment by hugohn** [comment]
Nunchuk is now completely open-source. @6102bitcoin
