### ISSUE TITLE
Content Suggestion: Atoms

### ISSUE THREAD

**Issue by raymonddurk** [bitcoin-only/bitcoin-only#357]
1) Link to Content: https://www.atoms.com/
2) Briefly Describe Content: The most comfortable everyday shoes available in quarter sizes.
3) Suggested Section: Spend Bitcoin page under Stores

**Comment by pardus79** [comment]
This site accepts altcoins for payment.

https://questions.atoms.com/en/articles/4658979-do-you-accept-cryptocurrency-payments
