### ISSUE TITLE
Update Suggestion: Update Amber Details

### ISSUE THREAD

**Issue by TheSvetski** [bitcoin-only/bitcoin-only#358]
**Please Describe Suggested Update:**

Hey mate.
A few updates:

1) Website is now: https://amber.app
2) Amber offers Buy, Sell, DCA, Withdrawals and Cold Storage as a Service
3) We're launching a membership version of Amber called "Amber Black". It's kind of a new product, just built off the base product. I feel like it needs it's own listing. Have a look at hw it works here:

https://amber.app/amber-black/

Let me know what u think.
Aleks

**Comment by pardus79** [comment]
NACK on having two listings.

But the amber-black page does list and compare both plans, so perhaps just list that page?

**Comment by 6102bitcoin** [comment]
ACK on updating link

NACK on two links, presumably users of amber will see links for upgrading to black?

**Comment by TheSvetski** [comment]
What’s ACK & NACK?

**Comment by ndalliard** [comment]
> What’s ACK & NACK?

ACK: Acknowledged
NACK: Not Acknowledged

**Comment by 6102bitcoin** [comment]
Updated the [link](https://github.com/bitcoin-only/bitcoin-only/commit/60103a78bb17de9a37b6c4c5ca83f243c3904908) & [description](https://github.com/bitcoin-only/bitcoin-only/commit/94e476e15251aa3f66004e85e00908e8318c8029).

**Comment by TheSvetski** [comment]
Thanks bro 🙏🏽
