### ISSUE TITLE
Content Suggestion: New DCA Calculator 

### ISSUE THREAD

**Issue by TheSvetski** [bitcoin-only/bitcoin-only#359]
1) Link to Content: https://amber.app (although we're going to migrate it to its' own page and beef up the features soon)
2) Briefly Describe Content: DCA Calculator
3) Suggested Section: Next to DCABTC.com in the Buy Bitcoin section perhaps?

**Comment by 6102bitcoin** [comment]
Currently the user must scroll through a significant amount of Amber advertisement to get to the DCA calculator. Unless this changes it is unsuitable for listing as it is effectively an advert.
