### ISSUE TITLE
Discussion: Non bitcoin-only sponsors.

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#363]
## Current Requirement: Strict bitcoin-only requirement for all sponsors of listings.
The current listing criteria for all listings is not only for the tool / service to be bitcoin-only, but also for **any sponsors** to also be bitcoin only. 

There was a [recent discussion](https://github.com/bitcoin-only/bitcoin-only/issues/344) about whether to de-list SLP for having a non bitcoin-only sponsor (hodl hodl, who have altcoin stablecoins) was had, without a satisfactory conclusion. 

I have thus far left SLP listed, mainly due to my inaction, the fact we are friends and his historic significant contribution. Clearly, inaction and friendship should not affect listing criteria, therefore a clarification is needed.

His latest adverts no longer specifically mention the altcoin stablecoins by name, so that is an improvement. That said, hodlhodl is still a sponsor, and they still have altcoin stablecoin support.

I can see a number of paths forward;

1. Delist SLP and maintain current criteria (All listing sponsors must be bitcoin-only)
2. Continue listing SLP and allow listings to have sponsors which support altcoin **stablecoins ** (and only stablecoins, not altcoins) provided the listing does not encourage the use of such stablecoins.
3.  Continue listing SLP and allow listings to have sponsors which support altcoins provided they provide a net benefit.

Please suggest any other alternative options below, along with your preference.

**Comment by wiz** [comment]
I don't see how this is even relevant. SLP doesn't "support altcoins" as per the standard listing requirements. If one of SLP's sponsors does support altcoins, then fine, don't list the sponsor on bitcoin-only, but that's not related to SLP being listed on bitcoin-only

**Comment by 6102bitcoin** [comment]
Thanks for your thoughts. 

I assume your vote is 4. Continue listing SLP and allow listings to have any sponsor?

What if a podcast had Coinbase as a sponsor? What if they had bitcoin(dot)com or some shitcoin foundation? 

As an aside, perhaps it is not explicitly listed, but I have only allowed listings if the sponsors are also bitcoin only (hence why btcsessions, among others, were not listed). As such, clarification either way is required.

**Comment by pardus79** [comment]
I think there is more nuance than just if a sponsor supports stable or altcoins. Exchanges that sell altcoins are easy to exclude. Hardware wallet companies that support multiple coins but have Bitcoin-only firmware that the podcaster encourages one to use is borderline. What if a pod sponsor sells bitcoin only-themed merch, but accepts an alt for customer payments? Many podcasts encourage users to use BtcPayServer, which has altcoin support, but we wouldn't remove any for doing that.

I like option 1, but I also want SLP to stay listed. I also think there are some good pods like Sessions that should be added despite the sponsors.

The rule could just be that in the case of podcasts, when there is something in question like this, there is discussion before a decision is made. The quality of the podcast as a whole should be weighed against who their sponsors are and how the podcast frames the ads when it comes to any altcoin support their sponsors have.

**Comment by pardus79** [comment]
Bitcoin Audible now has 2 sponsors that support altcoins:
BitBox - Hardware wallet (https://shiftcrypto.ch/coins/)
lvl.co - Exchange that supports buying altcoins. (https://support.lvl.co/hc/en-us/articles/360043419852-Crypto-Wallet)

**Comment by 6102bitcoin** [comment]
Thanks for the update. 

Perhaps we just say that although listed podcasts / videos are bitcoin only their sponsors may not be

**Comment by CypherPoet** [comment]
I think this is something that should be evaluated on a case-by-case basis.

Blanket-delisting anyone with an altcoin sponsor seems like it would be an extremely costly maintenance burden (Tracking all sponsors of all listings now and in the future... And for each sponsor, do they, now or in the future, "support" altcoins?).

Furthermore, I think the degree to which a sponsor weighs on someone's individual "Bitcoin Only" status can vary. If it's one sponsor out of five that has some affiliation with an altcoin, but the individual under consideration only mentions them in the context of Bitcoin, that's considerably different than, say, proudly shilling Coinbase 😄.

**Comment by pardus79** [comment]
I think that's a good idea. Should we move them to the bottom of the page in a separate list?

**Comment by pardus79** [comment]
Just noting that Saif's Bitcoin Standard podcast has an exchange that supports alts as a sponsor too.

His should go in a separate section as well.

**Comment by 6102bitcoin** [comment]
After some reflection on this I think it is going to be a significant amount of work to vet all sponsors continually. As such, either we should remove / separate out any projects with alt supporting sponsors or we should just ignore sponsors and only focus on the actual content. 

My preference would be the former, but I think it is likely too much work, so for now let's do the latter.
