### ISSUE TITLE
Meetup Suggestion: **Bitcoin Dubai Meetup**

### ISSUE THREAD

**Issue by hx4bc** [bitcoin-only/bitcoin-only#368]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoin Dubai
2.  Location Of Meetup: Dubai, United Arab Emirates
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/Bitcoin-Dubai/
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: @FarooqAhmedX
- Links showing public support: >>> https://twitter.com/FarooqAhmedX/status/1339937329729957889
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Just posted a [tweet Asking for Feedback](https://twitter.com/BitcoinOnly_/status/1340417878743506944)

Will review once there are some replies.

**Comment by 6102bitcoin** [comment]
Apparently meetups are currently happening weekly. I am happy to ACK and revert if there are valid complaints.

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/d92612d1a17c941ab9623a4849ef9fad4d60be1c)
