### ISSUE TITLE
Content Suggestion: Stackin Sat

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#369]
1) Link to Content: https://www.stackinsat.com/ 
2) Briefly Describe Content: French bitcoin purchasing?
3) Suggested Section: get-bitcoin

**Comment by pardus79** [comment]
Checked out the site with the help of translation. Looks good and bitcoin-only. Appears to be for the entire EU, not just France.

**Comment by 6102bitcoin** [comment]
Great - Thansks @pardus79 

I have [tweeted](https://twitter.com/BitcoinOnly_/status/1341429672245141506) a request for feedback.

**Comment by 6102bitcoin** [comment]
Very positive responses in public and in direct messages from people I trust. ACK

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/8b6a88f718830fa428fd3580757e7485baee14900)
