### ISSUE TITLE
Add Sparkswap to Get Bitcoin section

### ISSUE THREAD

**Issue by joe-rodgers** [bitcoin-only/bitcoin-only#37]
Consider adding [Sparkswap](https://sparkswap.com/) to [Get Bitcoin](https://bitcoin-only.com/#get-bitcoin).

From the website:
Sparkswap Desktop is the first cryptocurrency exchange built on the Lightning Network. Buy BTC with USD from your bank account in an instant.

**I dug into the GH repo and see that a LTC version of the project has been archived. I have not personally used the service, it popped up on my Twitter feed today.**

https://sparkswap.com/
https://twitter.com/sparkswap

**Comment by 6102bitcoin** [comment]
Looks like they have litecoin remnants in the code (perhaps because LND has it built in)

Have messaged the founder to find out if this is their long term plan.

**Comment by 6102bitcoin** [comment]
I was wrong. 
That code was for an old project, sparkswap desktop is bitcoin only.

https://github.com/sparkswap/sparkswap-desktop

**Comment by 6102bitcoin** [comment]
Uses 'Anchor' stablecoin on a shitcoin network.
