### ISSUE TITLE
Content Suggestion: HangarSix - Play Warzone. Earn Bitcoin.

### ISSUE THREAD

**Issue by brmdbr** [bitcoin-only/bitcoin-only#370]
1) Link to Content: https://www.hangarsixgaming.com/
2) Briefly Describe Content: HangarSix is a lightning based Call of Duty: Warzone tournament platform.
3) Suggested Section: get-bitcoin earn?

**Comment by 6102bitcoin** [comment]
Interesting idea. ACK

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/beedac7681d31c65dfdea30cde442c8c36f0fa94)
