### ISSUE TITLE
Content Suggestion: What Is Money Show

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#371]
1) Link to Content: https://www.youtube.com/watch?v=4rvTppy1qLI&list=PL2jAZ0x9H0bRvoNt1xNJWYa9_8_an03h0
2) Briefly Describe Content: Robert Breedlove's youtube show about money and Bitcoin
3) Suggested Section: Video podcasts

**Comment by 6102bitcoin** [comment]
ACK

**Comment by 6102bitcoin** [comment]
Added
