### ISSUE TITLE
Content Suggestion: List of Bitcoin Consultants

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#373]
1) Link to Content: N/A
2) Briefly Describe Content: List of individuals / companies which offer bitcoin consulting services.
3) Suggested Section: New Section?

**Comment by 6102bitcoin** [comment]
+ https://keykeeperira.com/bitcoin/

**Comment by wiz** [comment]
This is a bad idea IMO. We previously had a "people" page on Bitcoin Only that we had to take down because it was too controversial about who was a Bitcoiner or Shitcoiner, and endorsing "Bitcoin consultants" sounds like we will get many requests from scammers to be listed on the site.

**Comment by 6102bitcoin** [comment]
You are probably correct.
