### ISSUE TITLE
Content Suggestion: Bitcoiner Consulting

### ISSUE THREAD

**Issue by YttriumOx** [bitcoin-only/bitcoin-only#374]
1) Link to Content: https://www.bitcoinerconsulting.com/
2) Briefly Describe Content: Consultant focused on business/enterprise space.  Also offers training courses/classes.
3) Suggested Section: As per #373 add a "Consultant" section; before then, "Learning" (Classes subsection).

**Comment by 6102bitcoin** [comment]
Thank you - do you have any customers who can contact me with their feedback?

**Comment by YttriumOx** [comment]
I'm just in the process now of getting testimonials for the website.  When I do, I'll let you know.
Many of my customers prefer to remain anonymous for obvious reasons, but I'm sure I can find some.

**Comment by 6102bitcoin** [comment]
Apologies. We have [decided](https://github.com/bitcoin-only/bitcoin-only/issues/373#issuecomment-751519906) not to list consultants.
