### ISSUE TITLE
Content Suggestion: Entropy

### ISSUE THREAD

**Issue by jakesyl** [bitcoin-only/bitcoin-only#375]
1) Link to Content: https://entropy.rocks
2) Briefly Describe Content: A bitcoin-only block explorer and analytics platform
3) Suggested Section: Network page

**Comment by 6102bitcoin** [comment]
ACK

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/compare/0543610d27ea...4226b71e1490)
