### ISSUE TITLE
Content Suggestion: StoringBitcoin.info

### ISSUE THREAD

**Issue by AbelLykens** [bitcoin-only/bitcoin-only#384]
Some weeks ago I started StoringBitcoin.info , an objective site without sponsoring, to help people determine how to store their bitcoin. Visit the site or look at https://github.com/storingbitcoin-info/website#overview to get an idea of "paths" one can take. It's Bitcoin only.

1) Link to Content: https://storingbitcoin.info/
2) Briefly Describe Content: StoringBitcoin helps you finding your strategy for storing Bitcoin
3) Suggested Section: I'm afraid it does not really fit an existing category, learning might be the best fit but not 100%

**Comment by 6102bitcoin** [comment]
I like the concept, but the requirement for new users to enter sensitive information (how they are storing their bitcoin, if they deem this a large amount, if they are using a hardware wallet etc.) concerns me - these answers could be logged by a malicious server and tied to the users IP address.

For this reason I would feel uncomfortable merging this.

**Comment by AbelLykens** [comment]
Thanks for the feedback and opening of issues on the github, will take a good look at them.

Just as with those online wallet generators, one could run the site locally. Everything someone does happens client side. There is no tracking, no statistics. The server can not know what someone clicked on.

Of course you will have to trust me to not put this in at a later phase, that's something I can't technically fix but it's something I can vouch to not do...

Does this background/info help?

**Comment by 6102bitcoin** [comment]
Thanks - I understand that. Would you consider adding instructions to run through it locally at the start? I suppose a wget would work

**Comment by AbelLykens** [comment]
Will look at that and come back to you.

**Comment by AbelLykens** [comment]
Have added instructions for running offline. It's a github zip-download of the MASTER of the repo. It works (English only though). Added instructions at the start of the site :).

Please reconsider adding the site :smile:

**Comment by 6102bitcoin** [comment]
Seems like a good solution! ACK

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/dbfa0c93702a081db7ceac65cea887f64d7e34b4)

Will be visible in next site rebuild

**Comment by AbelLykens** [comment]
Thanks man! Much appreciated.
