### ISSUE TITLE
Meetup Suggestion: **Bitcoin Charlotte**

### ISSUE THREAD

**Issue by partyp** [bitcoin-only/bitcoin-only#385]
## Required:
1. Name of Meetup: Bitcoin Charlotte
2.  Location Of Meetup: Charlotte, NC, USA
3. At least one of the following:
- Meetup Page (or similar): http://www.meetup.com/BitcoinCharlotte
- Telegram Group (or similar): https://t.me/joinchat/GRK-_ZZ8Qz7U34nB
- Website: https://bitcoincharlotte.org

## Optional 
- Name of Organiser(s) & Twitter Handle: @Bitcoin_CLT
- Links showing public support: >>>  [example](https://twitter.com/Bitcoin_CLT/status/1352712860888129542?s=20)
- Tweet your commitment 
- Instagram: https://www.instagram.com/bitcoincharlotte/

```
As the organiser of Bitcoin Charlotte Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Thank you!

[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/e523c13fd46b5cb2545fc374770a2ee8e9bc384f)

We have not yet automated the build process, so it is not yet live on the site. We will build and update the site in the near future.
