### ISSUE TITLE
Feature Suggestion: Art Section?

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#388]
Are there enough bitcoin artists to merit a dedicated page?

e.g. https://en.pboy-art.com/

**Comment by pardus79** [comment]
I don't think so. But most of the bitcoin artists also sell things via their sites, so maybe an artists section on the spend bitcoin page would be better.

The one you listed shouldn't be added though. They list that they do NFTs on ETH - https://en.pboy-art.com/nfts
