### ISSUE TITLE
Content Suggestion: Bitcoin from theory to practice

### ISSUE THREAD

**Issue by bitcoin-in-action** [bitcoin-only/bitcoin-only#390]
1) Link to Content: https://amzn.to/2Ym4gz6 (Amazon) https://bit.ly/3ijAyC4 (accept bitcoin) (direct)
2) Briefly Describe Content: 

Technical info read

Bitcoin. Money for nerds? Digital gold? Perhaps, but certainly it is a social revolution. This is what the two authors think, after they put into practice the Bitcoin protocol with real and concrete examples. Their mantra is: "To thoroughly understand any technology, we must touch it with our hands and see with our own eyes the results we can achieve". They were not satisfied with superficially knowing what a transaction is and how it is identified in the blockchain, or why the merkle tree is used, or how private keys are managed in the deterministic wallet. They wanted to obtain each result step by step and explain all its connotations. So, fasten your seatbelts, because you are about to embark on a journey into cypherspace. Upon your return you will be aware of why Bitcoin has the credentials to shift the world balance. You don't need to be a miner to start mining as you don't need to be a developer to understand that it is no more time to ignore it.

3) Suggested Section: https://bitcoin-only.com/books

**Comment by 6102bitcoin** [comment]
Would it be possible to get access to a pdf to evaluate? If so, please DM me on twitter / keybase

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e56bee860b4af94f6665579d07e0dc511aa2f2b3)
