### ISSUE TITLE
Content Suggestion: Bitcoin 199 questions

### ISSUE THREAD

**Issue by bitcoin-in-action** [bitcoin-only/bitcoin-only#391]
1) Link to Content: https://amzn.to/3fB4Kbs (Amazon) https://www.corsobitcoin.com/prodotto/book-bitcoin-199-questions/ (Accept bitcoin) (Direct)
2) Briefly Describe Content: No Technical. Questions and Answers using few rows

We cannot stand still. We cannot be witnesses of history, just watching this train passing by.It is not acceptable to be parasites of this technology.This is the moment to try to understand how the greatest payment revolution works. Bitcoin is the answer to the eternal question, is the change that society has been waiting for since the dawn of time.How we can be really free from any bonds, independent from institutions, masters of our own life.In order to truly understand how some bits can turn the world upside down, we need to take the path towards knowledge, starting from scratch.We are sure that this short book will arouse both beginners’ and experts’ curiosity and provide the answers everyone needs.

3) Suggested Section:  https://bitcoin-only.com/books

**Comment by 6102bitcoin** [comment]
Would it be possible to get access to a pdf to evaluate? If so, please DM me on twitter / keybase

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/381082137bc9466322c4dd299fc55c6b19909cca)
