### ISSUE TITLE
Content Suggestion: Technical Videos about Bitcoin

### ISSUE THREAD

**Issue by bitcoin-in-action** [bitcoin-only/bitcoin-only#392]
1) Link to Content: https://www.youtube.com/BitcoinInAction
2) Briefly Describe Content: Technical Videos about Bitcoin. We Analyze the protocol with practice. Italian Language.
3) Suggested Section: https://bitcoin-only.com/videos

**Comment by 6102bitcoin** [comment]
Looks good. I would like to get an Italian speaker to verify that this is bitcoin-only

**Comment by alessandro-aglietti** [comment]
> Looks good. I would like to get an Italian speaker to verify that this is bitcoin-only

Indeed, all the content is bitcoin-only!

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/12b0ec1380a54e565205e448b9860405e22780da)
