### ISSUE TITLE
Meetup Suggestion: Holly Springs, NC Meetup

### ISSUE THREAD

**Issue by dmp1ce** [bitcoin-only/bitcoin-only#395]
I am committed to hosting a small weekly meetup in Holly Springs, NC intended to help people get started using Bitcoin and meeting trading partners.

## Required:
1. Name of Meetup: Holly Springs Meetup Group
2.  Location Of Meetup: Holly Springs, NC
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/holly-springs-bitcoin-meetup-group/

## Optional 
- Name of Organiser(s) & Twitter Handle: @Dave_Parrish
- Tweet your commitment: https://twitter.com/Dave_Parrish/status/1354810724325810185?s=20

**Comment by 6102bitcoin** [comment]
Thanks! [Added](https://github.com/bitcoin-only/bitcoin-only/commit/e4f2d81d2b75da0b2a669fc65e08dcdf60a88c49)

Will be merged next time we rebuild the site!
