### ISSUE TITLE
Update Suggestion: Wallets Page Arrangement

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#404]
**Please Describe Suggested Update:**

We currently have 
- OnChain, Open-source Non-custodial wallets with OnChain at a minimum (may also have lightning)
- Lightning, Open-source Non-custodial wallets with Lightning at a minimum (may also have OnChain)
- Closed Source, Wallets that are closed source, regardless of OnChain or Lightning 
- Custodial Accounts, Wallets that are Custodial
- Advanced Storage Methods

I think we should have
- All-in-one, Non-Custodial Hybrid (Non-Custodial Lightning + Non-Custodial OnChain)
- OnChain, Non-Custodial Onchain only
- Lightning, Non-Custodial Lightning only
--- Text explaining risks of custodial and closed source ---
- Non-Custodial Onchain + Custodial Lightning
- Custodial Ligtning only
- Closed Source 

Thoughts?

**Comment by pardus79** [comment]
Are there any non-custodial lightning wallets that don't have on-chain support?
