### ISSUE TITLE
Update Suggestion: Link to Diverter's Mining for the Streets

### ISSUE THREAD

**Issue by econoalchemist** [bitcoin-only/bitcoin-only#406]
**Please Describe Suggested Update:**
DESCRIBE UPDATE HERE
Please update the hyper link at https://bitcoin-only.com/get-bitcoin > "guide"

from: https://diverterbtc.keybase.pub/Mining%20for%20the%20Streets.pdf?dl=1

to: https://diverter.hostyourown.tools/mining-for-the-streets/

**Comment by pardus79** [comment]
Thanks!
