### ISSUE TITLE
Content Suggestion: 21Million Co Store

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#408]
1) Link to Content: https://21million.co/
2) Briefly Describe Content: Bitcoin Apparel 
3) Suggested Section: Spend Bitcoin > Stores

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/d0a6e7a48575466598204e313028c20fe8cc74bc)
