### ISSUE TITLE
Content Suggestion: Bitcoin Meetup

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#410]
1) Link to Content: link found here: https://twitter.com/_Bosch_/status/1362077347541704713
2) Briefly Describe Content: Perth Meetup
3) Suggested Section: Meetups

**Comment by pardus79** [comment]
Is it just a telegram channel?

**Comment by 6102bitcoin** [comment]
It is the same meetup as before, just now organised on telegram.
[Merged](https://github.com/bitcoin-only/bitcoin-only/compare/d0a6e7a48575...0189b75545cc)
