### ISSUE TITLE
Meetup Suggestion: Sovereign Club

### ISSUE THREAD

**Issue by karozagorus** [bitcoin-only/bitcoin-only#411]
A decentralized society for Freedom Maximalists who love #Bitcoin, family, and traditional values. Absolutely zero shitcoining is tolerated.

## Required:
1. Name of Meetup: Sovereign Club
2.  Location Of Meetup: On Matrix Chat Server at #SovereignClub:matrix.org or #FeedomMaxmialists:matrix.org
3. At least one of the following: 
- Matrix Chat: https://matrix.to/#/#SovereignClub:matrix.org
- Website: sovereign.club

## Optional 
- Name of Organiser(s) & Twitter Handle: https://twitter.com/SovereignClub_ https://twitter.com/LaserHodl
- Gab handle: SovereignClub
- Links showing public support: >>> https://bitcoinmagazine.com/articles/a-world-to-come

**Comment by 6102bitcoin** [comment]
@wiz & @pardus79 do you think we should have a groups page separate to meetups, or a groups section on the meetups page?

**Comment by pardus79** [comment]
There is a Cyberspace section on the Meetups page I think this can be listed under.

When this part of the list starts to get filled-up, it may make sense to create a separate page for online communities like this.

**Comment by karozagorus** [comment]
We are an online space just like bItCoInfRenemies is, so I thought we can get added.

**Comment by pardus79** [comment]
@karozagorus Please confirm there was a typo in your initial suggestion. I couldn't find "feedommaxmialists:matrix.org" but it looks like "FreedomMaximalists:matrix.org" is a valid room.

If so, I'm going to list it as https://app.element.io/#/room/#FreedomMaximalists:matrix.org so that it is clearer how users can navigate there.

**Comment by karozagorus** [comment]
> @karozagorus Please confirm there was a typo in your initial suggestion. I couldn't find "feedommaxmialists:matrix.org" but it looks like "FreedomMaximalists:matrix.org" is a valid room.
> 
> If so, I'm going to list it as https://app.element.io/#/room/#FreedomMaximalists:matrix.org so that it is clearer how users can navigate there.

Oh yeah, it was changed to #SovereignClub:matrix.org but I told them to keep #FreedomMaximalists:matrix.org too. Let me change it.

**Comment by karozagorus** [comment]
Okay, Laser gave me some stuff to add, so I added them. Should be good now!
