### ISSUE TITLE
Content Suggestion: Zaprite.com

### ISSUE THREAD

**Issue by john-magill** [bitcoin-only/bitcoin-only#416]
1) Link to Content: https://zaprite.com
2) Briefly Describe Content: Bitcoin invoicing and task management.
3) Suggested Section: Get Bitcoin -> Earn

**Comment by pardus79** [comment]
This may be better at https://bitcoin-only.com/store-tools

**Comment by john-magill** [comment]
Sure, this could work. I'm good with that.

**Comment by 6102bitcoin** [comment]
Interesting idea with a very nice design.

Some feedback;
- No option to pay in bitcoin to signup
- No option to denominate invoice amount in bitcoin
- Person paying can click paid invoice and there is no check that the address has actually been paid

Until you launch fully I will list it as (Beta)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/7c58adff8d143a1431b0d603759440c7dca4ecda)

Please notify when fully launched
