### ISSUE TITLE
Update Suggestion: URL update

### ISSUE THREAD

**Issue by nclapham** [bitcoin-only/bitcoin-only#418]
**Please Describe Suggested Update:**

Privacy -> Other Information -> Hodl Privacy (6102bitcoin)

Update URL to: https://6102bitcoin.com/faq-hodl-privacy/

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/8ac9014c28a58752cdbeb1f4f17c69bef49c1568)
