### ISSUE TITLE
Possible Addition of Security Section

### ISSUE THREAD

**Issue by ghost** [bitcoin-only/bitcoin-only#42]
Per suggestion of 6102, possibly we add a section devoted to Security.  Up for discussion where.

**Comment by 6102bitcoin** [comment]
I think this is definitely a good idea.

Some things can be moved into here from existing pages (e.g. glacier & casa wealth management pdf). It can be a hub for detailed information about how to use bitcoin securely including my hodl FAQ and seed FAQ.

**Comment by 6102bitcoin** [comment]
Been >1 year without progress. Closing for now.
