### ISSUE TITLE
Content Suggestion: 10x Security Bitcoin Guide

### ISSUE THREAD

**Issue by moritzwietersheim** [bitcoin-only/bitcoin-only#420]
1) Link to Content: https://btcguide.github.io/
2) Briefly Describe Content: Michael Flaxman's guide on how to store bitcoin without any single point of failure. https://twitter.com/mflaxman/status/1301605083969392641
3) Suggested Section: Advanced Storage Methods in https://bitcoin-only.com/wallets

**Comment by 6102bitcoin** [comment]
Great suggestion! [Added](https://github.com/bitcoin-only/bitcoin-only/commit/12fc6e1c87a00f5544def375d6d52829dd4fc518)
