### ISSUE TITLE
Content Suggestion: Bitcoin and Lightning Network on Raspberry Pi

### ISSUE THREAD

**Issue by brakmic** [bitcoin-only/bitcoin-only#422]
1) Link to Content: https://www.apress.com/gp/book/9781484255216
2) Briefly Describe Content: a technical book on using Bitcoin and Lightning Network on Raspberry Pi (models 3, 4 and Zero).
3) Suggested Section:  books

**Comment by 6102bitcoin** [comment]
Thanks - Please can you send me a pdf copy of the book to review ([keybase](https://keybase.io/6102), [email](sixoneohtwo@protonmail.com))

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/48ba808b5d8790d294c95d8a26414c6869cb4b6c)
