### ISSUE TITLE
Content Suggestion: Start9 Labs Embassy

### ISSUE THREAD

**Issue by kn0wmad** [bitcoin-only/bitcoin-only#423]
1) Link to Content: start9labs.com
2) Briefly Describe Content: Personal shelf-top computer for self-hosting open source software.  Plug-n-play, featuring Core, BTCProxy, LND, c-lightning, BTCPayServer
3) Suggested Section: Hardware

**Comment by 6102bitcoin** [comment]
Good suggestion, Thanks. [Added](https://github.com/bitcoin-only/bitcoin-only/commit/acaac2f82826a2fe133520003d9649bdefd9185b)

**Comment by kn0wmad** [comment]
Thank you for the addition!  I probably should have mentioned that the Embassy has a DIY option as well - https://docs.start9labs.com/getting-started/diy.html

**Comment by 6102bitcoin** [comment]
Thanks [Added](https://github.com/bitcoin-only/bitcoin-only/commit/68bf504ba2f6eb060b359a59e7e956a9d16d3721)!
