### ISSUE TITLE
Meetup Suggestion: Redding Bitcoin Meetup

### ISSUE THREAD

**Issue by doowta** [bitcoin-only/bitcoin-only#426]
100% bitcoin only. Focus on educating and building the bitcoin community in Redding and beyond. 

## Required:
1. Name of Meetup: Redding Bitcoin
2.  Location Of Meetup: Redding, California
3. At least one of the following:
- Meetup Page (or similar): https://meetu.ps/c/4xRp8/GrBqM/d
- Website: bitcoinredding.org (coming soon)

## Optional 
- Name of Organiser(s) & Twitter Handle: Michael Atwood @dooowta

**Comment by 6102bitcoin** [comment]
Thanks! [Added](https://github.com/bitcoin-only/bitcoin-only/commit/abd1ba762c50aab71f16d9081055f09c4a0dda51)
