### ISSUE TITLE
Update Suggestion: Spend Bitcoin | Store suggestion - https://BTCBD.club

### ISSUE THREAD

**Issue by mineyour-biz** [bitcoin-only/bitcoin-only#430]
[BTCBD.club](https://BTCBD.club) is a CBD brand and online shop for customers in the USA that offers only one product: **full spectrum CBD**, cold processed at a facility with a patent pending for it's unique clean oil separation process. 
No ethanol, and no high pressure CO2 processing.

CBD isolate (with the THC fully stripped out), is shown to be less effective, and be processed in much harsher ways.

- [BTCBD.club](https://BTCBD.club) offers only _real_ CBD _(full spectrum)_.
- [BTCBD.club](https://BTCBD.club) accepts only Bitcoin.

In the future, the only additional product offered will be higher capacity bottles of the same cold processed full spectrum CBD.
In the future, the only additional coin accepted will be Bitcoin over Lightning Network.

**Comment by 6102bitcoin** [comment]
Thanks - We currently only list stores that sell bitcoin specific products (not stores that simply accept bitcoin) due to the amount of work that would be required to list all niche stores. If this changes we will add your store. Thanks
