### ISSUE TITLE
Content Suggestion: Bitcoin Merch

### ISSUE THREAD

**Issue by bitcoin-geardotcom** [bitcoin-only/bitcoin-only#432]
1) Link to Content: https://www.bitcoin-gear.com
2) Briefly Describe Content: We're the N°1 bitcoin only merchandise store on the web, operating since 2017.
3) Suggested Section: Spend Bitcoin, Stores

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/6a02e1d0fa59ba0cd7a1daf311f5f145ccb024a5)
