### ISSUE TITLE
Content Suggestion: Abuela Mami Coffee

### ISSUE THREAD

**Issue by pardus79** [bitcoin-only/bitcoin-only#434]
1) Link to Content: https://abuelamamicoffee.com/
2) Briefly Describe Content: Coffee Beans
3) Suggested Section: Spend Bitcoin

**Comment by 6102bitcoin** [comment]
We currently only list stores that sell bitcoin specific products (not stores that simply accept bitcoin) due to the amount of work that would be required to list all niche stores. If this changes we can add this store.
