### ISSUE TITLE
Content Suggestion: Hellodime BTC Educational Card Game

### ISSUE THREAD

**Issue by anonymoustrident** [bitcoin-only/bitcoin-only#439]
1) Link to Content: [HelloDime URL](https://www.hellodime.com/) 
2) Briefly Describe Content: This project (fully self funded, no trashy VC backing ) has an intention to kickstart interest and get individuals to be more interested in the Bitcoin ecosystem . The concept of the game is on your keys, your coins with most of the high level BTC concepts within the game mechanics (mining/ scarcity / randomness / difficulty ) alongside personas that emulate real world scenarios. 
3) Suggested Section: hardware/other hardware ?

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/ec9efca0e78713060324e0426d735ef69163768c)

Thanks!

**Comment by anonymoustrident** [comment]
Thanks. Didn’t see it but it’s okay.
