### ISSUE TITLE
Content Suggestion: BitcoinTV.com

### ISSUE THREAD

**Issue by wiz** [bitcoin-only/bitcoin-only#440]
1) Link to Content: https://bitcointv.com/
2) Briefly Describe Content: a citadel of video content for the bitcoin community
3) Suggested Section: Videos

**Comment by 6102bitcoin** [comment]
https://github.com/bitcoin-only/bitcoin-only/commit/1e9864b7fdbe4173cbfd45cb4a04148ba3a0dcd7
