### ISSUE TITLE
Content Suggestion:  Libbitcoin wiki

### ISSUE THREAD

**Issue by andhan360** [bitcoin-only/bitcoin-only#441]
1) Link to Content: https://github.com/libbitcoin/libbitcoin-system/wiki/Cryptoeconomics
2) Briefly Describe Content: This started as a way to avoid retyping the same ideas, 140 characters at a time. In keeping with that environment, topics were as short as possible, and informal. Most of the topics (including this one) were written on my phone, on a flight, train or in a coffee shop. Many are quick observations that arise from intimate knowledge of core Bitcoin code or long self-study and experience in various disciplines. - Eric Voskuil
3) Suggested Section: https://voskuil.org/cryptoeconomics/

**Comment by 6102bitcoin** [comment]
Great suggestion. Thanks

https://github.com/bitcoin-only/bitcoin-only/commit/21bc39ac49ca7d7433e44a1b78cbb170f6bcdd13

**Comment by andhan360** [comment]
Thx sry Link to the book was meant for suggested section under books and the libbitcoin wiki itself as learning resource
