### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by Jayzio** [bitcoin-only/bitcoin-only#443]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Miami Bitcoiners
2.  Location Of Meetup: 
609 Brickell Ave.
Miami FL
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/miamibitcoiners/
- Telegram Group (or similar): https://t.me/miamibitcoiners
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle:  Jon Chenot  @jonchenot
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of Miami Bitcoiners Meetup Meetup I can confirm that the meetup is bitcoin-only. 
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups. 
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Great - Thanks!

https://github.com/bitcoin-only/bitcoin-only/commit/8a5d845576d644c83a1ad1ad95bc7094ebc451b9
