### ISSUE TITLE
Content Suggestion: Bitcoin Dev Kit (BDK)

### ISSUE THREAD

**Issue by notmandatory** [bitcoin-only/bitcoin-only#445]
1) Link to Content: https://bitcoindevkit.org/
2) Briefly Describe Content: Rust bitcoin wallet library
3) Suggested Section: Dev Tools -> Backend Tools

**Comment by 6102bitcoin** [comment]
Great suggestion! Thanks

https://github.com/bitcoin-only/bitcoin-only/commit/59e5832ed05ade22a26114f8465ce3d9d67bef57
