### ISSUE TITLE
Content Suggestion: Pocket Bitcoin

### ISSUE THREAD

**Issue by TKone7** [bitcoin-only/bitcoin-only#446]
1) Link to Content: [pocketbitcoin.com](https://pocketbitcoin.com/)
2) Briefly Describe Content:
Pocket exchanges your bank payments automatically into bitcoin. The bitcoin are then sent directly into your own Bitcoin wallet. You can also set up a recurring payment to automate your buys (DCA). Pocket also helps people getting started on their Bitcoin journey by guiding them through the process of buying and storing their bitcoin. Pocket provides different hardware storage options. 
3) Suggested Section: Get Bitcoin
Description: Buy; Location: EU; Auto DCA: Yes

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/d6eb8df1512817e59570278556a9a985075490cd)

Thanks
