### ISSUE TITLE
Content Suggestion: Spanish lessons

### ISSUE THREAD

**Issue by Camilojdl** [bitcoin-only/bitcoin-only#447]
1) Link to Content: https://twitter.com/CamiloJdL/status/1403105925112635392?s=20
2) Briefly Describe Content: Come join my Spanish lessons for Bitcoin maxis by a Bitcoin maxi. 
We learn using bitcoin examples and have fun while doing it. 
Memes included. 
No shitcoin talk allowed.
Only ENG + SPA. 

Flag of SpainVolcanoFlag of ArgentinaBeach with umbrellaFlag of El Salvador

3) Suggested Section: learning

**Comment by 6102bitcoin** [comment]
Thank you for making me aware of this initiative. Please can you walk me through what happens when someone joins the telegram group.

**Comment by 6102bitcoin** [comment]
Closing due to lack of response
