### ISSUE TITLE
Meetup Suggestion: San Diego Bitcoiners

### ISSUE THREAD

**Issue by inpharmaticist** [bitcoin-only/bitcoin-only#448]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: San Diego Bitcoiners
2.  Location Of Meetup: San Diego, CA
3. At least one of the following:
- Meetup Page (or similar): meetup.com/sdbitcoiners
- Telegram Group (or similar): #sdbitcoiners:matrix.org
- Website: sdbitcoiners.com

## Optional 
- Name of Organiser(s) & Twitter Handle: Corey @inpharmaticist
- Links showing public support: >>> 
- Tweet your commitment 
https://twitter.com/sdbitcoiners/status/1402331053549711360?s=20

https://twitter.com/sdbitcoiners/status/1402374788861992964?s=20

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e6cd2d0630b617622707519944b65df08b2ed501)

Thanks!
