### ISSUE TITLE
Boost Bitcoin circulation, Million Transactions Per Second with stronger privacy

### ISSUE THREAD

**Issue by raymaot** [bitcoin-only/bitcoin-only#449]
https://raymo-49157.medium.com/time-to-boost-bitcoin-circulation-million-transactions-per-second-and-privacy-1eef8568d180

I have a proposal for improve Bitcoin TPS and privacy.

**Comment by 6102bitcoin** [comment]
Thanks for sharing. Some questions;

- What stops the creditor maliciously publishing the GT despite the issuer acting in good faith?
- How does CPFP affect this?
- Email Address would be best avoided if possible

>  We suppose the miners always control transactions with doc-watchers and avoid accepting transaction with same UTXO but different output.

This is quite an assumption.

**Comment by raymaot** [comment]
Hi, 
Thanks for your reply
What stops the creditor maliciously publishing the GT despite the issuer
acting in good faith? 
The economic lose prevents creditors to send GT to Bitcoin network.
Since the creditor would lose 70% of his fund in favor of miner fee in
GT, meanwhile issuer will lose 15% of his output.
How does CPFP affect this? 
Any external action like RBF or CPFP must be economically convenient to
be considered as a threat to protocol, otherwise it is a possibility of
an irrational action(wasting funds) that no one can avoid the other from
hurting himself. after all, this protocol intended to use for very small
amount (less than 20,000 Satoshi worth), so in worth case, the attacker
can hurt the other side 20,000 Sat. since the system is distributed Bots
or mass attack scenarios won't work on this model.
Email Address would be best avoided if possible 
Email can be replaced (or parallely exist) by central servers or some
peer-to-peer IP based system. It is only a communication mechanism which
I still prefer email because I have a particular point of view about
this project and its future features.

We suppose the miners always control transactions with doc-watchers and
avoid accepting transaction with same UTXO but different output.
This is quite an assumption.
Yes, it is a wish which we can ask Bitcoin developers as a BIP.

Would you like to engage more in project and help it?

**Comment by 6102bitcoin** [comment]
Unfortunately I do not have time to explore this. Good luck
