### ISSUE TITLE
Content suggestion: Add 21bitcoin.app

### ISSUE THREAD

**Issue by bitsani** [bitcoin-only/bitcoin-only#452]
1. Link to Content: https://21bitcoin.app
2. Briefly Describe Content: Austrian Bitcoin Only Startup focused on Auto DCA, (German) education and making Bitcoin accessible to people in the EU.
3. Suggested Section: GET BITCOIN (Buy other)

**Comment by 6102bitcoin** [comment]
How long have you been operating for?

**Comment by pardus79** [comment]
Looks like it's still waitlist and hasn't launched.

**Comment by 6102bitcoin** [comment]
Thanks. @bitsani  Please open a new issue when you have launched
