### ISSUE TITLE
Content Suggestion: NAME OF CONTENT TO BE ADDED

### ISSUE THREAD

**Issue by ashishb** [bitcoin-only/bitcoin-only#453]
1) Link to Content: https://ashishb.net/all/stanford-cs251-cryptocurrencies-blockchains-and-smart-contracts/
2) Briefly Describe Content: Stanford CS 251 cryptocurrency course notes
3) Suggested Section: https://bitcoin-only.com/learning-resources

**Comment by 6102bitcoin** [comment]
Thanks for the suggestion. A quick check shows that it is not bitcoin-only.
