### ISSUE TITLE
Content Suggestion: THNDR GAMES

### ISSUE THREAD

**Issue by jackeveritt** [bitcoin-only/bitcoin-only#454]
1) Link to Content: https://thndr.games
2) Briefly Describe Content: Lightning Gaming - Win bitcoin playing mobile games via the Lightning Network
3) Suggested Section: Get Bitcoin

**Comment by 6102bitcoin** [comment]
Both games look to enter the gamer into a raffle. What are the odds of winning?

**Comment by jackeveritt** [comment]
Hey! Correct. As long as the user collects 1 ticket in the game, they are guaranteed 10 sats (at time of writing).

We also do weekly tournaments where users compete in the games for sats prizes. Here is an example of a tournament:

https://thndr.games/event/roadtrip016 (already finished)

Here is our twitter where we post about these tournaments https://twitter.com/thndrgames 

We were the first commercial lightning network games on the App Store and Google Play

More information about our back story in this article https://www.btctimes.com/news/lightning-game-startup-thndr-games-surpasses-100000-downloads

:)

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/81876ac429b0248f742788ffdb03133cdba9e06f) to new Win section of get-bitcoin page
