### ISSUE TITLE
Update Suggestion: request to add bitcoinreserve.com to bitcoin-only.com/get-bitcoin

### ISSUE THREAD

**Issue by johnyukon21** [bitcoin-only/bitcoin-only#458]
**Please Describe Suggested Update:**
Bitcoin Reserve is a new Bitcoin only on-ramp in the EU. Requesting to be added to https://bitcoin-only.com/get-bitcoin.

**Comment by johnyukon21** [comment]
Just to be upfront. We are bitcoin only (no alt/shitcoins will ever be listed). However, we do have plans to enable Liquid BTC and interaction (for buying and selling Bitcoin) with stablecoins on Liquid.

**Comment by 6102bitcoin** [comment]
Thank you. [Added](https://github.com/bitcoin-only/bitcoin-only/commit/3820029fbe40160e54306762395522ef9615b609)

**Comment by johnyukon21** [comment]
Thank you!
