### ISSUE TITLE
Content Suggestion: Bitcoin Italian Podcast

### ISSUE THREAD

**Issue by mbelletti** [bitcoin-only/bitcoin-only#459]
1) Link to Content: https://bitcoinitaliapodcast.it/
2) Briefly Describe Content: Bitcoin Italian Podcast
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Quick glance of website shows large Shitcoin price widget. Can't verify the podcast is bitcoin-only and this suggests that is unlikely.
