### ISSUE TITLE
Meetup Suggestion: **Minnepolis Bitcoin Meetup**

### ISSUE THREAD

**Issue by bquittem** [bitcoin-only/bitcoin-only#460]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoiners in Minneapolis
2.  Location Of Meetup: Minneapolis (multiple venues based on weather and format)
3. At least one of the following:
- Meetup Page (or similar): https://twitter.com/BitcoinersMPLS
- Telegram Group (or similar): https://t.me/joinchat/SWd5ZeVCAhGpZIjh
- Website: n/a

## Optional 
- Name of Organiser(s) & Twitter Handle: Brandon Quittem // https://twitter.com/Bquittem
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment We've been hosting meetups monthly for 23 months. Bitcoin only. Here's recent tweet announcing meetup next week https://twitter.com/Bquittem/status/1415441814933344266?s=20

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/934bacbf469b8069b96d522b0754bbe7aa520608)
