### ISSUE TITLE
Meetup Suggestion: Bay Bitcoin Meetup

### ISSUE THREAD

**Issue by evolve-tm** [bitcoin-only/bitcoin-only#461]
1. Name of Meetup: Bay Bitcoin Meetup
2.  Location Of Meetup: San Francisco Bay Area
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/bay-bitcoin-meetup/?success=groupSetup

- Name of Organiser(s) & Twitter Handle: https://twitter.com/thomasbtc 
- Tweet your commitment - https://twitter.com/thomasbtc/status/1414659662377459735?s=20

**Comment by 6102bitcoin** [comment]
Can't see much discussion about this online. Will wait for photos / confirmation that the meetup is happening regularly

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/93fb49e77223efa3daebccafde1cf45b65abc4d5)

**Comment by evolve-tm** [comment]
Sorry but could we please update the group link to - https://www.meetup.com/bay-area-bitcoiners - It is the same group of people. We were running two different meetup pages and this one has more people.
