### ISSUE TITLE
Content Suggestion: Priced in Bitcoin

### ISSUE THREAD

**Issue by pricedinbtc** [bitcoin-only/bitcoin-only#464]
1) Link to Content: https://www.pricedinbitcoin21.com
2) Briefly Describe Content: Priced in Bitcoin denominates various assets in Bitcoin, including precious metals such as Gold and Silver, public companies such as Apple and Tesla, ETFs (Exchange Traded Funds) such as Select Sector SPDR ETFs and iShares Treasury and Corporate Bond ETFs.
3) Suggested Section: Explorers and Dashboards or Learning Resources

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/3d46eaa9e5fe80173354363eae9c2172ecbd33d2)
