### ISSUE TITLE
Content Suggestion: Flitz

### ISSUE THREAD

**Issue by kiwiidb** [bitcoin-only/bitcoin-only#465]
1) Link to Content: https://getflitz.app
2) Briefly Describe Content: European Lightning-only self-custody-oriented DCA platform / Bitcoin broker.
3) Suggested Section: Get Bitcoin

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/cd144fa7863b81afc801c25cfc2c91da5234d635)
