### ISSUE TITLE
Meetup Suggestion: Old City Bitcoiners

### ISSUE THREAD

**Issue by farscapian** [bitcoin-only/bitcoin-only#466]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Old City Bitcoiners
2.  Location Of Meetup: St. Augustine, Jacksonville, Jacksonville Beach area
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/old-city-bitcoiners/
- Telegram Group (or similar): https://www.oldcity-bitcoiners.info / https://matrix.to/#/#public:oldcity-bitcoiners.info [note there is an existing invite-only telegram group for Old City Bitcoiners, though I hope to convince people to switch]
- Website: https://www.oldcity-bitcoiners.info

## Optional 
- Name of Organiser(s) & Twitter Handle: @farscapian
- Links showing public support: https://twitter.com/farscapian/status/1374381350233407493?s=20
- Tweet your commitment: https://twitter.com/farscapian/status/1419757365117739012?s=20

**Comment by 6102bitcoin** [comment]
Awesome! [Added](https://github.com/bitcoin-only/bitcoin-only/commit/dfc91987f1c525e2cffa408e9b3984777142f716)
