### ISSUE TITLE
Barcelona Bitcoin Meetup

### ISSUE THREAD

**Issue by federicociro** [bitcoin-only/bitcoin-only#467]
1. Name of Meetup: Bitcoin Barcelona meet up
2.  Location Of Meetup: Barcelona, Spain
3. At least one of the following:
- Telegram Group (or similar): https://t.me/joinchat/Oklz_GwSGCQyOTJk

## Optional 
- Name of Organiser(s) & Twitter Handle: @FedericoCiro1
- Links showing public support: >>>  [Bitcoin Node and support!](https://twitter.com/FedericoCiro1/status/1417055695216726023?s=19)

```
As the organiser of [Bitcoin Barcelona] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Hi Federico, 

Sounds good!

Your twitter account is private so I can't see the linked tweet. Want to follow me (@6102bitcoin on twitter) and I'll check it out.

**Comment by 6102bitcoin** [comment]
Added. Please update  us if the meetup has stopped.
