### ISSUE TITLE
Addition of Bitcoin Jobs Section

### ISSUE THREAD

**Issue by ghost** [bitcoin-only/bitcoin-only#47]
Addition of Jobs section for Bitcoin Only companies.  Would be a nice reference point for Developers and more looking for Jobs in the Space.

**Comment by 6102bitcoin** [comment]
I like the idea but it may require significant maintenance and would rely on companies contacting bitcoin-only to have jobs taken down once filled which may not regularly happen.

I remember that Justin Moon made a twitter thread not long ago where companies commented if they were looking for applicants. We could use that list as a starting point if we decide maintenance won't be an issue.

**Comment by PuraVlda** [comment]
Hmmm, yea i tend to agree with the maintenance part of this. I was scrolling through Twitter and saw his feed, that is what made me think about it.

**Comment by 6102bitcoin** [comment]
Hard to maintain. Closing.
