### ISSUE TITLE
Content Suggestion: Bitcoin Stimulus YouTube

### ISSUE THREAD

**Issue by bsimon6288** [bitcoin-only/bitcoin-only#471]
1) Link to Content: https://www.youtube.com/channel/UCI6gR1ViAl7hJ2NNOg7S5yA
2) Briefly Describe Content: Engaging animated bitcoin videos
3) Suggested Section: Videos

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/18c15f33b3247a54a8b4aac385a57a7a8bee87bd)
