### ISSUE TITLE
Content Suggestion: BitcoinStimulus.net

### ISSUE THREAD

**Issue by bsimon6288** [bitcoin-only/bitcoin-only#472]
1) Link to Content: https://www.bitcoinstimulus.net/
2) Briefly Describe Content: Tracking the value of the $1200 stimulus check if used to buy bitcoin
3) Suggested Section: Explorers and Dashboards 'Metrics'

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/18c15f33b3247a54a8b4aac385a57a7a8bee87bd)
