### ISSUE TITLE
Meetup Suggestion: Houston Bitcoin Meetup

### ISSUE THREAD

**Issue by benthecarman** [bitcoin-only/bitcoin-only#473]
## Required:
1. Name of Meetup: Houston Bitcoin Meetup
2.  Location Of Meetup: Houston, Texas, USA
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/houston-bitcoin-meetup-group/
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: Al's Lacrosse https://twitter.com/lacrosse_al
- Links showing public support: >>>  https://twitter.com/parkeralewis/status/1423806125061836801
- Tweet your commitment: https://twitter.com/benthecarman/status/1407377715192373253

**Comment by 6102bitcoin** [comment]
Thanks! [Added](https://github.com/bitcoin-only/bitcoin-only/commit/92369165e1c094ec09b7a74da5af5e3d2f0d53db)
