### ISSUE TITLE
Content Suggestion: Bitcoin Brothers

### ISSUE THREAD

**Issue by bitcoin-bear** [bitcoin-only/bitcoin-only#474]
1) Link to Content: https://www.bitcoinbrothers.io
2) Briefly Describe Content: Homebrewed, family-operated podcast with two brothers and one mission: Bitcoin.
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
[https://github.com/bitcoin-only/bitcoin-only/commit/ba7dec25977c36f24950500161b9fa99dac7d353](Added!)

Thanks
