### ISSUE TITLE
Content Suggestion: Adopting Bitcoin - A Lightning Summit in El Salvador

### ISSUE THREAD

**Issue by moritzwietersheim** [bitcoin-only/bitcoin-only#476]
1) Link to Content: https://adoptingbitcoin.org/
2) Briefly Describe Content: Adopting Bitcoin - A Lightning Summit in El Salvador / 16-18 November 2021 - The adoption of Bitcoin in the Republic of El Salvador caused excitement around the world. It’s time to shine! Adopting Bitcoin is bringing together the Bitcoin and Lightning community in San Salvador and El Zonte to create connections and foster the future of money and payments in the Central American republic.
3) Suggested Section: https://bitcoin-only.com/conferences

Great Website - love it :)
Cheers, Moritz

**Comment by wiz** [comment]
Feel free to make a PR

**Comment by Victornwafada** [comment]
Bitcoin
 “Many of life’s failures are people who did not realize how close they were to success when they gave up." Join me and earn more in Tmf-investments..
https://tmf-investments.com/?ref=Gregorymorris1

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/22d64b4d97f66bb2014ba1b877650a3fe7e0ce05)

Thanks
