### ISSUE TITLE
Content Suggestion: embit bitcoin library

### ISSUE THREAD

**Issue by moritzwietersheim** [bitcoin-only/bitcoin-only#477]
1) Link to Content: https://embit.rocks/#/
2) Briefly Describe Content: embit is a bitcoin library designed to run either with Python 3 on a PC or with MicroPython on embedded devices. For cryptography it uses libsecp256k1 library maintained by Bitcoin Core team for elliptic, and everything else is implemented in python. 
3) Suggested Section: https://bitcoin-only.com/dev-tools

Stepan would be very happy to see his library added here - Specter DIY, Seedsigner & some others are using it already :)
Cheers, Moritz

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/282dca1b701b56ccacf586cbba8cd8b60e1b03a0).

Thank you
