### ISSUE TITLE
Meetup Suggestion: Cleveland Bitcoin Meetup

### ISSUE THREAD

**Issue by bitstime** [bitcoin-only/bitcoin-only#483]
## Required:
1. Name of Meetup: Cleveland Bitcoin Meetup
2.  Location Of Meetup: Cleveland, Ohio
3. At least one of the following: 
- Telegram Group (or similar): https://t.co/CmsGSsNgF8?amp=1

## Optional 
- Name of Organiser(s) & Twitter Handle: BitcoinCLE

```
As the organiser of Cleveland Bitcoin Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by MaxSikorski** [comment]
Please add. Glad we could gather a group together to jump-start the Cleveland meetup.

**Comment by 6102bitcoin** [comment]
Added
