### ISSUE TITLE
Meetup Suggestion: LincolnLand Bitcoin Meetup

### ISSUE THREAD

**Issue by MaxDruthers** [bitcoin-only/bitcoin-only#491]
1) Link to Content: [t.me/LincolnlandBTCMeetup](url)
2) Briefly Describe Content: Bitcoin has the potential to change the world in more ways than just "number go up". Based in Springfield, Illinois, we explore its various positive social impacts while furthering our own understanding of all things Bitcoin...
3) Suggested Section: https://twitter.com/BTCLincolnLand

**Comment by 6102bitcoin** [comment]
Thanks. [Added](https://github.com/bitcoin-only/bitcoin-only/commit/65924672f512e1adb845e2ad4b5d03732ff9c3bb)
