### ISSUE TITLE
Update Suggestion: Amber 

### ISSUE THREAD

**Issue by NGUmonster** [bitcoin-only/bitcoin-only#495]
**Please Describe Suggested Update:**
Hi 6102bitcoin,
Would you mind to update Amber's location from "Australia" to "USA & Australia", please?

Linked to the site from Reddit at least 1,000 times in the past year. Keep it awesome and Bitcoin ONLY, please.

**Comment by 6102bitcoin** [comment]
Bump @NGUmonster

**Comment by NGUmonster** [comment]
Just came across this tweet (the US launch confirmed in the comments). https://twitter.com/JWWeatherman_/status/1465120597256646660

It seems like it was in beta until a couple of days ago.

**Comment by 6102bitcoin** [comment]
ok. Ready to be made into a pull request.

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/pull/580/commits/4d139f8d5cf8275f87781f08bc3bc04bd33a772a)
