### ISSUE TITLE
Content Suggestion: January 3rd Podcast

### ISSUE THREAD

**Issue by sohrabsameny** [bitcoin-only/bitcoin-only#497]
1) Link to Content: https://jan3podcast.com/
2) Briefly Describe Content: A Podcast in Persian language; which have been started from primary to advanced concepts of the Bitcoin Network. This Podcast is focused only on describing Bitcoin and never have talked about anything else. 
Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Waiting on user feedback. Please direct your listeners to comment here https://twitter.com/BitcoinOnly_/status/1455243945987002380
