### ISSUE TITLE
Content Suggestion: Unchained Capital

### ISSUE THREAD

**Issue by stephen-unchained** [bitcoin-only/bitcoin-only#498]
1) Link to Content: unchained.com
2) Briefly Describe Content: Unchained's open source tools and financial services leverage the bitcoin protocol to deliver safe, easy-to-use, and transparent products that empower clients to hold private keys in multisig wallets.  Build-it-yourself [multisig vaults](https://unchained.com/vaults/) with Unchained 3rd key collaborative custody and Caravan backup are no-fee.
3) Suggested Section: https://bitcoin-only.com/wallets

**Comment by wiz** [comment]
feel free to make a PR 👍🏻

**Comment by 6102bitcoin** [comment]
Was merged. Closing
