### ISSUE TITLE
Update Suggestion: Swan

### ISSUE THREAD

**Issue by NGUmonster** [bitcoin-only/bitcoin-only#499]
Just realised Swan Bitcoin changed name to Swan. Here's the announcement:
https://twitter.com/SwanBitcoin/status/1453842805273481222

The header is saying Swan instead of Swan Bitcoin - https://www.swanbitcoin.com/

Listed here: https://bitcoin-only.com/get-bitcoin

**Comment by 6102bitcoin** [comment]
Done. Thanks
