### ISSUE TITLE
Merchant Processor

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#5]
Switch opennode out as recommended processor following KYC introduction.

Not clear what to switch to.

**Comment by 6102bitcoin** [comment]
BTCPayServer is great, but there is inbuilt support for shitcoins and thus it is not bitcoin only

**Comment by 6102bitcoin** [comment]
Removed banner for now [commit](https://github.com/bitcoin-only/bitcoin-only/commit/4de224392a746d6295d89d7f9ea6e3cfb6226c40)

**Comment by pavlenex** [comment]
Re-visiting this if there's still interest in listing btcpay on the site, the new default bitcoin only build which is the officially supported  and maintained https://blog.btcpayserver.org/btcpay-server-1-0-5-4/ is now available. 
So previous altcoin concerns should be addressed now, as altcoins are now maintained on a separate build.

**Comment by pardus79** [comment]
I'm a big Btcpayserver fan, but I think that still maintaining an altcoin build means the project is not bitcoin only.

**Comment by pavlenex** [comment]
I guess we failed the purity test. Will do better next time.

**Comment by wiz** [comment]
@pavlenex I think the main issue is sidetracking users to altcoins - would it be possible for you guys move all the altcoin stuff to a separate website? like btcpay-altcoins.com? then once the btcpay website is Bitcoin Only, I think you would qualify

**Comment by pavlenex** [comment]
No thanks, don't have time for that just to pass the purity test

altcoins aren't even mentioned on the site

don't really care about this anymore
