### ISSUE TITLE
Content Suggestion: Walltime

### ISSUE THREAD

**Issue by NGUmonster** [bitcoin-only/bitcoin-only#500]
1) Link to Content: https://walltime.info/
2) Briefly Describe Content: I personally never used this site, just looking for an exchange for someone living in Brazil and found it being listed here:
https://bitcoin.org/en/exchanges#south-america
3) Suggested Section: https://bitcoin-only.com/get-bitcoin

**Comment by 6102bitcoin** [comment]
Thanks. Requested a review https://twitter.com/BitcoinOnly_/status/1458583731988570115

**Comment by 6102bitcoin** [comment]
No feedback
