### ISSUE TITLE
Content Suggestion: Unchained Capital (OTC desk)

### ISSUE THREAD

**Issue by stephen-unchained** [bitcoin-only/bitcoin-only#502]
1) Link to Content: https://unchained.com/buy-bitcoin/
2) Briefly Describe Content: Unchained Capital has an OTC desk for Bitcoin buys via dedicated encrypted trading chat to quote and execute trades. Direct deposit to multisignature vaults that clients control. 
3) Suggested Section: https://bitcoin-only.com/get-bitcoin

**Comment by wiz** [comment]
sure, go ahead and make a pull request

**Comment by 6102bitcoin** [comment]
Merged. Thanks @wiz
