### ISSUE TITLE
Content Suggestion: Rabbit Hole Podcast

### ISSUE THREAD

**Issue by sohrabsameny** [bitcoin-only/bitcoin-only#506]
1) Link to Content: https://anchor.fm/RHJ
2) Briefly Describe Content: Persian Podcast about Bitcoin
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
Added - Thanks

**Comment by Ziya-Sadr** [comment]
I'm the owner of the podcast, it's called "Lane Khargoosh" meaning "Rabbit Hole" in English.. maybe you can add the farsi title along with it so it won't be confused with other content that use the same name

suggestions:

Rabbit Hole Podcast/Lane Khargoosh
Rabbit Hole Podcast (Lane Khargoosh)
Rabbit Hole Podcast (Farsi)
Lane Khargoosh (Rabbit Hole Podcast)

or any other way you guyz deem it better to be presented to users
