### ISSUE TITLE
Content Suggestion: ₿PAY

### ISSUE THREAD

**Issue by BTCPsrld** [bitcoin-only/bitcoin-only#508]
1) Link to Content: pay.bitcoinpeople.it
2) Briefly Describe Content: non-custodial payment proccessor
3) Suggested Section: Store tools

**Comment by 6102bitcoin** [comment]
Please can you provide more information

**Comment by davecl16** [comment]
BPay is a product offered by Bitcoin People, an italian company focused on Bitcoin.
BPay is a payment processor open-source, based on BTCPayServer.

https://www.bitcoinpeople.it/bpay

**Comment by davecl16** [comment]
Yes, it is an instance of BTCPayServer, with our customization.

**Comment by davecl16** [comment]
Bitcoin People is in this list: https://directory.btcpayserver.org/

**Comment by davecl16** [comment]
Any updates?

**Comment by davexbtc** [comment]
Hi @6102bitcoin, any update?

**Comment by davexbtc** [comment]
In this page, there is our **customization**: https://docs.btcpayserver.org/Development/Theme/#2-bootstrap-themes

**Comment by wiz** [comment]
I don't understand, why we would list a specific instance of BTCPayServer on bitcoin-only?

**Comment by davexbtc** [comment]
Ok, I got it. Thanks.
