### ISSUE TITLE
Requirement: Meetups

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#51]
Great to hear you want to be listed on bitcoin-only.com/#meetups

To ensure the meetups listed are actually bitcoin only we require a meetup organiser to 
1) Tweet that the meetup is bitcoin-only
2) Reply to that tweet with a link to the website/chat/meetup page used to organise the meetup.

```
**Example Draft Tweet** *(Feel free to use):**

As the organiser of [XXX] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not featured in talks/presentations at our meetups.
#bitcoinonlymeetups
```

Once completed raise a GitHub Issue or DM/Tag [@bitcoinonly_](https://twitter.com/bitcoinonly_)

**Note:
- If you can't tweet this then you are not a bitcoin-only meetup. You may be a great meetup, but you are not eligible to be listed on the site.
- The tweet must stay up. If it gets deleted you get delisted. This is to avoid people posting to get temporarily listed and then deleting the post and promoting altcoins.**

**Comment by michaelfolkson** [comment]
I don't want to get involved in a flame war because it is not a good use of time for either of us. I support what you are trying to do but feel the above is poorly worded for those who are focused on the technology rather than the investment opportunity. However, as a suggestion a draft tweet I would be happy with: 

"As the organiser of [XXX] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are only discussed within the context of educational learnings for the Bitcoin project such as if they contain features that may be merged into Bitcoin in future
#bitcoinonlymeetups

**Comment by michaelfolkson** [comment]
I suspect this would allow some of the best technical meetups focused on Bitcoin to be able to be listed on your site. It really is dumb not to have NYC BitDevs, SF Bitcoin Devs, Bitcoin Lab Berlin etc on your site as they are the best technical Bitcoin meetups in the world. There are a bunch of others too: https://bitcoinmagazine.com/articles/op-ed-want-to-learn-about-bitcoin-try-a-local-socratic-seminar

**Comment by 6102bitcoin** [comment]
Hi @michaelfolkson,

Thanks for taking the time to share your thoughts.

I appreciate what you say, and I agree that there are some meetups which are not listed which have historically hosted some fantastic talks & are generally great for newcomers and more experienced bitcoiners alike. 

The reason that the current requirement does not include your suggestion is that it is challenging to **remotely** determine whether a meetup allows talks which explain how some technology used by an altcoin is useful as opposed to talks explaining how the technology could be useful **for bitcoin**. 

Often, those most eager to present the benefits of a technology used by an altcoin are also involved with the governance / issuance of the altcoin and are incentivised to create market demand with such presentations. 

I can't attend all meetups, I can't review every talk. As such, I need a mechanism to allow me to list only meetups which have a low likelihood of altcoin promotion - something I think that the users of bitcoin-only expect. 

I accept that there are flaws with the current mechanism. For example, talks about mistakes made in altcoin projects and how these mistakes can be avoided in bitcoin projects would be a potentially valuable topic that would not be allowed at a meetup attempting to meet the current requirement. Similarly theoretically there could be changes made in altcoins which provide valuable learnings about things that could be added to bitcoin (though I am not aware with any examples of features which have followed this path - do you have any in mind?).

I anticipate that your suggested change would greatly increase the number of meetups listed which allow talks which are actual altcoin promotion. I would rather have clear rules which mean that some good meetups are not listed than make arbitrary exceptions or have rules which altcoin-promoting meetups appear to meet. 

A simple change that I have previously considered would be to relax the rules on the understanding that if it is shown that the meetup hosted a presentation which was promoting an altcoin it is removed. I decided not to do this because some would claim that presenting the technical facts about an altcoin isn't 'altcoin promotion', and therefore doesn't break the rules, but it clearly wouldn't be in-line with the mission and purpose of bitcoin-only, and wouldn't be something that bitcoin-only.com users would expect to see from a bitcoin-only meetup.

If you (or anyone else) has any ideas about how to manage my concerns I am very open to hearing them.

Thanks,
6102

**Comment by michaelfolkson** [comment]
Personally I think you are making this way more complicated than it needs to be. Don't allow the promotion of any coin or token as an investment other than Bitcoin. Don't allow sponsorships from foundations, projects with their own coin or token. But free reign to discuss how other coins and projects technologically compare to Bitcoin and whether technologies like zero knowledge proofs (Zcash) and Mimblewimble (Grin, Beam) should or could ever be merged into Bitcoin. Those are two examples where exciting new technology was experimented with on an independent blockchain as it was not sufficiently mature or well tested for Bitcoin.

**Comment by 6102bitcoin** [comment]
Created [Meetup Issue Template](https://github.com/bitcoin-only/bitcoin-only/issues/new?assignees=&labels=meetup&template=meetup-suggestion.md&title=Meetup+Suggestion%3A+%2A%2AExample+Bitcoin+Meetup%2A%2A) which aims to make the position clear on this.
