### ISSUE TITLE
Content Suggestion: Ziya Sadr's Youtube Channel 

### ISSUE THREAD

**Issue by Ziya-Sadr** [bitcoin-only/bitcoin-only#512]
1) Link to Content: https://www.youtube.com/c/ZiyaSadr
2) Briefly Describe Content: Weekly bitcoin QnA Sessions, Software guides and tutorials in Persian
3) Suggested Section: Videos>Tutorials

**Comment by 6102bitcoin** [comment]
Added, Thanks
