### ISSUE TITLE
SatSale Payment Processor/Donation Platform

### ISSUE THREAD

**Issue by SecretestSquirrel** [bitcoin-only/bitcoin-only#513]
**_Link to Content:_** https://github.com/nickfarrow/SatSale

**_About:_** SatSale currently serves as a:
- Donation page and button for your website that you can easily embed/link to anywhere
- Bitcoin payment gateway, including a Woocommerce plugin that easily turns any Wordpress site into a Bitcoin accepting store
- Versatile API and payments platform for both on-chain and lightning payments (supporting both clightning and lnd)
- No shitcoins. **Bitcoin only.**

**_Suggested Section:_** Store Tools/ Get Bitcoin

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/2d7231a945d70b96a71650f2c9dd7fa8d473ba2f)

Cheers!
