### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by Hacker123237656777334523457** [bitcoin-only/bitcoin-only#518]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: einundzwanzig MeetUps
2.  Location Of Meetup: https://einundzwanzig.space/meetups/ lots of cities
3. At least one of the following:
- Meetup Page (or similar): https://einundzwanzig.space/meetups/
- Telegram Group (or similar): https://einundzwanzig.space/meetups/ depends on city
- Website: einundzwanzig.space](https://einundzwanzig.space/)

## Optional 
- Name of Organiser(s) & Twitter Handle: https://twitter.com/fabthefoxx, https://twitter.com/_d11n_
- Links showing public support: >>>  [[example](https://twitter.com/6102bitcoin/status/1193203530150096897)](https://twitter.com/_einundzwanzig_)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Merged.](https://github.com/bitcoin-only/bitcoin-only/commit/319fc816691f265add275156f7ac8de3d20377fa)

If you know any of the meetup organisers added please have them reach out to us to be listed
