### ISSUE TITLE
Add DYI Bitcoin Hardware

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#52]
Idea of adding DYI Bitcoin HArdware site to Hardware Section maybe?  No specific spot for it yet, may need a note or new heading?  Ideas?

https://diybitcoinhardware.com/

**Comment by 6102bitcoin** [comment]
I think a sub section for DIY hardware is a good idea. Projects get added from this source plus any others we can find once they have been confirmed bitcoin-only. A note will explain that these DIY devices have typically undergone less thorough examination for being secure when compared to non DIY hardware devices (i.e. ColdCard)

**Comment by 6102bitcoin** [comment]
For now I have added this to the Hardware page
