### ISSUE TITLE
Content Suggestion: Spend Bitcoin - Store addition

### ISSUE THREAD

**Issue by bitcoinoriginals** [bitcoin-only/bitcoin-only#523]
1) Link to Content: https://bitcoinoriginals.shop/
2) Briefly Describe Content: Discrete classic bitcoin-only clothing and accessories for HODLers who value fashion as much as they do opsec
3) Suggested Section: Spend Bitcoin - Store

**Comment by 6102bitcoin** [comment]
According to the header on the linked page Bitcoin is not accepted. 

The page is for sites where you can spend bitcoin.
