### ISSUE TITLE
Update Suggestion: INDIANAPOLIS LINK IS INCORRECT

### ISSUE THREAD

**Issue by yunglerk** [bitcoin-only/bitcoin-only#524]
**Please change the Indianapolis link from the Telegram group of a Chicago meetup to the website "indybtc.com":**
The link for the Indianapolis meetup under "Indianapolis" is a telegram group for one of the Chicago meetups. The Indy Meetup group has a website at indybtc.com. We appreciate the change made thank you!

**Comment by 6102bitcoin** [comment]
[Fixed](https://github.com/bitcoin-only/bitcoin-only/commit/b09c402bc1c364e9b6a59bd1ff6dabcbc3b0a1bf)

Apologies
