### ISSUE TITLE
Bitcoin Day Sacramento

### ISSUE THREAD

**Issue by je7je** [bitcoin-only/bitcoin-only#525]
1) Link to Content: https://www.bitcoinday.io/sacramento22
2) Briefly Describe Content: Bitcoin Day is an interactive micro-conference to hear from local, regional, and national Bitcoiners on a variety of subjects such as how to buy and HODL privately and securely, building on Bitcoin, mining, self-sovereignty in the digital age, and leveraging local politics for Bitcoin.
3) Suggested Section: Conferences (February 19th, 2022)

**Comment by 6102bitcoin** [comment]
Added
