### ISSUE TITLE
Meetup Suggestion: Lexington Bitcoin Meetup

### ISSUE THREAD

**Issue by patrickulrich** [bitcoin-only/bitcoin-only#527]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Lexington Bitcoin Meetup
2.  Location Of Meetup: Lexington, KY
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/LexingtonBitcoin/
- Telegram Group (or similar): https://t.me/joinchat/9ZHtEJwK8VVmMzZh
- Matrix Group: https://matrix.to/#/!GyfMdcvxReQKrlvEYB:lexingtonbitcoin.org?via=lexingtonbitcoin.org
- Website: lexingtonbitcoin.org

## Optional 
- Name of Organiser(s) & Twitter Handle: Patrick Ulrich (@patrick_ulrich)
- Links showing public support: >>>  [example](https://twitter.com/patrick_ulrich/status/1476219405168254980)
- Tweet your commitment 

```
As the organiser of @lexbitcoinorg Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/152993b6736985462e5ab53c31c957c6c09b3d07) ([2](https://github.com/bitcoin-only/bitcoin-only/commit/9a9322878a8a3500d099cbe41917c9af917002ed))

Thanks!
