### ISSUE TITLE
Meetup Suggestion: **Brownsville Bitcoin Meetup**

### ISSUE THREAD

**Issue by jaimeadiez** [bitcoin-only/bitcoin-only#529]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Brownsville Bitcoin Meetup
2.  Location Of Meetup:  Brownsville, TX
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/brownsville-bitcoin/
- Telegram Group (or similar): https://t.me/brownsvillebitcoin
- Website: NA

## Optional 
- Name of Organiser(s) & Twitter Handle: https://twitter.com/jaimeandresdiez
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of Brownsville Bitcoin Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/14fcd5cf017fc630427a345594a60a921dc9e9b9)

Thanks!
