### ISSUE TITLE
Content Suggestion: Replace BLW with successor SBW

### ISSUE THREAD

**Issue by NCrashed** [bitcoin-only/bitcoin-only#531]
1) Link to Content: https://lightning-wallet.com/
2) Briefly Describe Content: The SBW wallet is an Android wallet with bundled LN node, LNURL, and LN-Auth support.
3) Suggested Section: As the BLW wallet is now deprecated and replaced with SBW by the author, I suggest replacing BLW in https://bitcoin.kyoto/wallets with SBW.

**Comment by 6102bitcoin** [comment]
[Done](https://github.com/bitcoin-only/bitcoin-only/commit/5a1681476cfa1abee288a25bb60747e3d3429c72)

Thanks
