### ISSUE TITLE
Bitcoin Support DIY self-custody guides

### ISSUE THREAD

**Issue by tristanborgess** [bitcoin-only/bitcoin-only#535]
1) https://guides.bitcoinsupport.com/
2) There are 4 DIY guides for bitcoin self-custody and privacy at the moment, all of which include the use of a passphrase: Blue wallet, Wasabi wallet, CoinJoin with Wasabi and Coldcard. 
3) Suggested Section: Learning resources

**Comment by 6102bitcoin** [comment]
[merged](https://github.com/bitcoin-only/bitcoin-only/pull/544) your pull

Thanks
