### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by jrman28** [bitcoin-only/bitcoin-only#536]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Rocket City Bitcoin Meetup
2.  Location Of Meetup: Huntsville, AL
3. At least one of the following:
- Meetup Page (or similar): https://meetu.ps/e/KF2G2/Dpqyd/i
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: 
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [Rocket City Bitcoin] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added Previously](https://github.com/bitcoin-only/bitcoin-only/commit/d28f572e1f5e37ec617b048bedcbaea28498055a)
