### ISSUE TITLE
Update Suggestion: update Stekking to Satsback.com

### ISSUE THREAD

**Issue by moonshot75** [bitcoin-only/bitcoin-only#537]
**Please Describe Suggested Update:**
Stekking and Satsback have joined forces and are now Satsback.com.

Please change "Stekking" into "Satsback.com" and "https://stekking.com/" into "https://satsback.com/" on page https://bitcoin-only.com/get-bitcoin under "Cashback Rewards".

We are the only cashback/satsback site that supports payouts with Lightning.
Is it also possible to change "Bitcoin cashback rewards" into "Bitcoin (Lightning) cashback rewards"?

**Comment by 6102bitcoin** [comment]
Can you make a pull request?

**Comment by moonshot75** [comment]
https://github.com/bitcoin-only/bitcoin-only/pull/549

**Comment by 6102bitcoin** [comment]
Merged
