### ISSUE TITLE
Content Suggestion: Lightning Store

### ISSUE THREAD

**Issue by ltngstore** [bitcoin-only/bitcoin-only#546]
1) Link to Content: http://lightning.store
2) Briefly Describe Content: Obscure Bitcoin pop culture/punk mashups for sale on ⛓ & ⚡️
3) Suggested Section: Spend Bitcoin

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/pull/555) with shorter description.

Thanks
