### ISSUE TITLE
Please add appmoon.io

### ISSUE THREAD

**Issue by jackeveritt** [bitcoin-only/bitcoin-only#55]
Please add https://appmoon.io

It is an android app store for bitcoiners.  All apps use the bitcoin lightning network for in app purchases.

Perhaps add to this section: 

Spend -> Fun and Play 

Thanks

**Comment by 6102bitcoin** [comment]
Thanks for submitting: I will aim to review in the next few weeks.

**Comment by pardus79** [comment]
In order to use this service, it appears a user has to install an apk on their phone, downloaded from the appmoon website. I could not find any open source repositories for appmoon, nor any app on the google play appstore or on Fdroid.

Installing an apk like this is a security risk.

**Comment by jackeveritt** [comment]
I am winding down this service now anyway. Closing
