### ISSUE TITLE
Content Suggestion: BTC22

### ISSUE THREAD

**Issue by bconfde** [bitcoin-only/bitcoin-only#557]
1) Link to Content: https://bconf.de/
2) Briefly Describe Content: Largest German-speaking Bitcoin conference in Europe
3) Suggested Section: Conferences ( September 15th-17th)

**Comment by 6102bitcoin** [comment]
Merged

**Comment by bconfde** [comment]
Thanks for listing it! Could you maybe change the title from "B Conf" to "BTC22"?
