### ISSUE TITLE
Meetup Suggestion: montrose bitcoin 

### ISSUE THREAD

**Issue by HODLorado** [bitcoin-only/bitcoin-only#565]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Montrose Bitcoin and Beers
2.  Location Of Meetup: San Juan Brews 
3. At least one of the following:
- Meetup Page (or similar): 
- Telegram Group (or similar): 
- Website:https://aegloff85.wixsite.com/montrosebitcoin

## Optional 
- Name of Organiser(s) & Twitter Handle:
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
The site will be added if you remove the blockfi reflink. Their attack against private bitcoin use is unacceptable.

**Comment by HODLorado** [comment]
Sounds good, I will remove the link when I get home on Tuesday. Thank you
for the tip. Could you expand further on their attack on privacy just for
my personal knowledge please?

**Comment by 6102bitcoin** [comment]
Thanks. I can't find any mention of a bitcoin meetup by @adam_egloff on twitter. Please can you post a tweet stating that you are the orgainser of the meetup with a link to it.

**Comment by HODLorado** [comment]
Done, thank you

**Comment by 6102bitcoin** [comment]
The website prompts a viewer to use platforms I can't support. The tweet has all the needed info so I have linked that.
Thank you
