### ISSUE TITLE
Content Suggestion: Smart Bitcoin Investments

### ISSUE THREAD

**Issue by lithiumgold** [bitcoin-only/bitcoin-only#569]
1) Link to Content: [https://www.smartbitcoininvestments.com](https://www.smartbitcoininvestments.com)
2) Briefly Describe Content: A large blog that teaches the subject of bitcoin investing
3) Suggested Section: Learning Resources -> Websites

**Comment by 6102bitcoin** [comment]
Thanks for raising the issue. This website is mainly refferal links and is not suitable for listing.
