### ISSUE TITLE
Content Suggestion: Add Podcast: Speaking of Bitcoin

### ISSUE THREAD

**Issue by relativisticelectron** [bitcoin-only/bitcoin-only#571]
1) Link to Content:  https://podcasts.google.com/feed/aHR0cDovL2ZlZWRzLnNvdW5kY2xvdWQuY29tL3VzZXJzLzM1MTM2NzYxLW1pbmR0b21hdHRlci90cmFja3M
2) Briefly Describe Content: Speaking of Bitcoin is a classic Bitcoin podcast, that should not be missing in the podcast recommendations.
3) Suggested Section: Add Speaking of Bitcoin to podcast list.

**Comment by 6102bitcoin** [comment]
Thank you for raising the issue. This podcast is not bitcoin only.
