### ISSUE TITLE
Update Suggestion: Remove "Revealer"

### ISSUE THREAD

**Issue by jevidon** [bitcoin-only/bitcoin-only#572]
**Please Describe Suggested Update:**
Revealer appears to be shutting down/has shut down. Consider removing their listing from https://bitcoin-only.com/hardware

**Comment by 6102bitcoin** [comment]
Thanks. [Done](https://github.com/bitcoin-only/bitcoin-only/pull/580/commits/9b6e85be018175ff80198641006e5a0538bcbb98)
