### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by Gmuney** [bitcoin-only/bitcoin-only#575]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Pleb Say
2.  Location Of Meetup: El Camino San Antonio Texas
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/sanantoniobitcoinclub/
- Telegram Group (or similar): San Antonio Bitcoin Club
- Website: sanantoniobitcoinclub.com

## Optional 
- Name of Organiser(s) & Twitter Handle: @SABTCclub
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Thanks [Merged](https://github.com/bitcoin-only/bitcoin-only/pull/580/commits/3ce685c410c9f80ebe79313deff7420fb908af20)
