### ISSUE TITLE
Meetup Suggestion: **JXN MISS Bitcoiners**

### ISSUE THREAD

**Issue by MississippiMatt** [bitcoin-only/bitcoin-only#576]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: JXN MISS Bitcoiners
2.  Location Of Meetup: Jackson, Mississippi
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/jxn-mississippi-bitcoin/
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: @MatthewABurrow
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [JXN MISS Bitcoiners] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
 
Yes, I can confirm the above statements are true of our JXN MISS Bitcoiners Meetup
- signed, Matthew A. Burrow

**Comment by 6102bitcoin** [comment]
Thanks. [Merged](https://github.com/bitcoin-only/bitcoin-only/pull/580/commits/4e6d56b1f0fd95b7b3ae463ab9924721cfe099ec)
