### ISSUE TITLE
Consider adding content to Privacy section

### ISSUE THREAD

**Issue by joe-rodgers** [bitcoin-only/bitcoin-only#58]
Consider adding [Protect your bitcoin through privacy](https://bitcoinsnippets.com/protect-your-bitcoin-through-privacy/) to the [Bitcoin Only - Privacy - Information](https://bitcoin-only.com/#privacy) section.

This is a "non-technical" guide to Bitcoin Privacy.
This website is a Bitcoin Only curation of r/bitcoin

**Comment by 6102bitcoin** [comment]
This is great!

**Comment by 6102bitcoin** [comment]
[merged](https://github.com/bitcoin-only/bitcoin-only/commit/ce7511283ed81f5d7fcb070b45842be4d42e7019)
