### ISSUE TITLE
Content Suggestion: Lightning labs substack

### ISSUE THREAD

**Issue by Bosch-0** [bitcoin-only/bitcoin-only#587]
1) Link to Content: https://lightninglabs.substack.com/
2) Briefly Describe Content: Monthly newsletter for lighting related updates. 
3) Suggested Section: https://bitcoin-only.com/learning-resources in the periodicals section

**Comment by 6102bitcoin** [comment]
Merged https://github.com/bitcoin-only/bitcoin-only/pull/620
