### ISSUE TITLE
Add xsats

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#59]
Consider adding Xsats.com 

Waiting: need user feedback

**Comment by xsats** [comment]
Thanks for opening the issue.
Specifically, what format/quantity of user feedback are you looking for? By now we’ve welcomed a few dozen active users, the vast majority of which are repeat clients - even in the short week that we’ve been active. We’re immensely humbled and grateful for the amount of positive feedback we’ve received directly from clients so far, but we’re not comfortable pressing our clients to publicly review given privacy implications (we will never dox our clients) amongst other reasons.

We’d love some guidance on what’d be involved in gaining representation on bitcoin-only. We also invite you to try out xsats.com first hand and/or have some trusted UK/European-based bitcoiners use and review our platform and get a feel for what we’re about.
Cheers!

**Comment by 6102bitcoin** [comment]
Sounds very reasonable.

As you say I need to get some trusted UK/European-based bitcoiners use and review your platform. 

Thank you for your patience

**Comment by xsats** [comment]
That would be great, thank you. They won’t be disappointed.

**Comment by xsats** [comment]
Hi again 6102, we’re eager to know if there’s any chance of a merge in time for the LNConf in Berlin this weekend.

We’re getting steady growth and are touched by all the positive feedback we’re getting. As mentioned before, almost all signups end up becoming repeat users.

Here’s a tiny taste of the feedback:
https://www.trustpilot.com/review/xsats.com

But as you know, Bitcoiners are a discrete and private breed, which might explain why we’re not getting a huge amount of public feedback. 

Did you get a chance to take a look at xsats or have a trusted bitcoiner try it out?

Cheers

**Comment by pardus79** [comment]
Reviewed their Telegram channel. Looks like this exchange stopped service a while back and is revamping for mobile before relaunch.

**Comment by pardus79** [comment]
Closing. When you relaunch, please open a new issue.
