### ISSUE TITLE
1. Grand Rapids Bitcoiners

### ISSUE THREAD

**Issue by RWSlot** [bitcoin-only/bitcoin-only#590]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: 
2.  Location Of Meetup: 
3. At least one of the following:
- Meetup Page (or similar): 
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle:
- Links showing public support: >>>  [example](https://twitter.com/6102bitcoin/status/1193203530150096897)
- Tweet your commitment 

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
Is there a link or a twitter account?

**Comment by 6102bitcoin** [comment]
https://github.com/bitcoin-only/bitcoin-only/issues/591

**Comment by RWSlot** [comment]
Twitter: @GRBTCEmail: ***@***.***: 6102bitcoin ***@***.***>Sent: Thursday, April 28, 2022, 17:30To: bitcoin-only/bitcoin-only ***@***.***>Cc: RWSlot ***@***.***>; Author ***@***.***>Subject: Re: [bitcoin-only/bitcoin-only] 1. Grand Rapids Bitcoiners (Issue #590)
Is there a link or a twitter account?
