### ISSUE TITLE
Meetup Suggestion: Grand Rapids Bitcoiners

### ISSUE THREAD

**Issue by RWSlot** [bitcoin-only/bitcoin-only#591]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Grand Rapids Bitcoiners
2.  Location Of Meetup: Founders
3. At least one of the following:
- Meetup Page (or similar): Twitter @GRBTC
- Telegram Group (or similar): t.me/GRBitcoiners
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: @RWSlot
- Links showing public support: >>> [ [example](https://twitter.com/6102bitcoin/status/1193203530150096897)](https://twitter.com/RWSlot/status/1513960669145714695?s=20&t=9YXlDE-eXCuB8pyb6WPdpw)
- Tweet your commitment 

```
As the organiser of Grand Rapids Bitcoin Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
https://twitter.com/grbtc/status/1513958273736757257
