### ISSUE TITLE
Content Suggestion: Illusive Moose influencer marketing platform

### ISSUE THREAD

**Issue by snow884** [bitcoin-only/bitcoin-only#597]
1) Link to Content: https://advertizing.illusive-moose.ca
2) Briefly Describe Content: 
Influencer marketing platform helping Bitcoin businesses attract more customers
3) Suggested Section: Store Tools

**Comment by snow884** [comment]
I wasn't sure if Store Tools is the best section for it, please let me know if you can think of a better one

**Comment by 6102bitcoin** [comment]
not suitable
