### ISSUE TITLE
Content Suggestion: COINBEAST.COM

### ISSUE THREAD

**Issue by CoinBeast** [bitcoin-only/bitcoin-only#599]
1) Link to Content: WWW.COINBEAST.COM
2) Briefly Describe Content: BLOGS, REVIEWS AND LEARNING TOOLS FOR BITCOIN EDUCATION
3) Suggested Section: LEARNING RESOURCES (WEBSITES)

**Comment by wiz** [comment]
There are price quotes for Ripple and Litecoin scrolling by at the bottom of the page, so is this really a Bitcoin Only website? 

Also it seems more like a content marketing website for affiliate referral links than an educational resource.

**Comment by CoinBeast** [comment]
The price ticker is there to provide some humour. All jokes aside, our
content is exclusively about Bitcoin. Our team includes Bitcoin maxis from
all over the world and our mission is adoption through education. We also
offer a 1:1 consulting service called CoinBeast Connect where users can
book a call with a Bitcoin Pro. Hope that clarifies some of the issues
you’ve raised. Let me know if you have any other questions.

Cheers,
Jon

**Comment by CoinBeast** [comment]
I should also mention that we produce a lot of free Bitcoin content on
Twitter, Clubhouse and Tik Tok.

**Comment by 6102bitcoin** [comment]
Not suitable for listing with that banner.
