### ISSUE TITLE
Add Host4coins 

### ISSUE THREAD

**Issue by PuraVlda** [bitcoin-only/bitcoin-only#61]
Ketominer's hosting solution for Privacy and Bitcoin only.

https://host4coins.net/

**Comment by 6102bitcoin** [comment]
Looks Awesome! Anyone tried it out yet?

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/e040affb5309b7788837387609313a0381a99326)
