### ISSUE TITLE
Meetup Suggestion: **Example Bitcoin Meetup**

### ISSUE THREAD

**Issue by BitcoinErrorLog** [bitcoin-only/bitcoin-only#611]
1. Name of Meetup: Lisbon Bitcoin Maximalists
2.  Location Of Meetup: Lisbon, Portugal
3. At least one of the following:
- Meetup Page (or similar): https://www.meetup.com/lisbon-bitcoin-maximalists/
- Telegram Group (or similar): 
- Website:

## Optional 
- Name of Organiser(s) & Twitter Handle: John Carvalho https://twitter.com/BitcoinErrorLog
- Links showing public support: >>>  [example](https://twitter.com/BitcoinErrorLog/status/1521375961794727936)
- Tweet your commitment 

```
As the organiser of [Lisbon Bitcoin Maximalists] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by wiz** [comment]
Okay cool please make a PR
