### ISSUE TITLE
Content Suggestion: btc++ conference

### ISSUE THREAD

**Issue by JayOceans** [bitcoin-only/bitcoin-only#612]
1) Link to Content: https://www.btcplusplus.dev/
2) Briefly Describe Content: btc++
is a bitcoin dev conf
3) Suggested Section: Conferences

**Comment by nickkrauts** [comment]
I just submitted a pull request to add this to the code. Thanks for the recommendation!

**Comment by 6102bitcoin** [comment]
Merged. thanks
