### ISSUE TITLE
Add devbitcoinshow

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#62]
German Bitcoin Show recommend for adding on [twitter](https://twitter.com/Bas_02/status/1179768838201716738?s=19)

Need to evaluate

**Comment by Conimous** [comment]
Bitcoin only show in Dutch. Hosted by ; @AaronvanW @JWBurgers @GKBoris 

Weekly new shows.

**Comment by 6102bitcoin** [comment]
[Added!](https://github.com/bitcoin-only/bitcoin-only/commit/4a3ad2da71cdd96de38f271097872a346bf8d3d5)
