### ISSUE TITLE
Add "Look Into Bitcoin" to learning

### ISSUE THREAD

**Issue by joe-rodgers** [bitcoin-only/bitcoin-only#63]
Consider [Look Into Bitcoin](https://www.lookintobitcoin.com/) to the learning section. 

This site is about learning Bitcoin valuation tools and models.

**Comment by 6102bitcoin** [comment]
Great find.

**Comment by 6102bitcoin** [comment]
[Added!](https://github.com/bitcoin-only/bitcoin-only/commit/c856c8bf528e03ca53454ed1e5a9c26f619ffb5b)
