### ISSUE TITLE
Bitcoin Cafe

### ISSUE THREAD

**Issue by aguf2001** [bitcoin-only/bitcoin-only#65]
[www.bitcoin.cafe](url)

Find a coffe place full of bitcoiners to buy and sell BITCOIN with cash in your city. KYC should not be required to acquire bitcoin. Ever! http://www.bitcoin.cafe

**Comment by 6102bitcoin** [comment]
It's a nice idea. Let's keep an eye on it and if it spreads to more locations I'll add it.

**Comment by aguf2001** [comment]
Yes! Sure! Thanks!
