### ISSUE TITLE
Meetup Suggestion: Honolulu BitDevs

### ISSUE THREAD

**Issue by Rob-Ferguson** [bitcoin-only/bitcoin-only#655]
## Required:
1. Name of Meetup: Honolulu Bitcoin Developers
2.  Location Of Meetup: Honolulu
3. At least one of the following:
- Meetup Page (or similar): https://meetu.ps/c/4SS7m/M2dkz/a
- Telegram Group (or similar): https://t.me/+Uh9gbHO9EHFkZWJh
- Website: http://www.honolulubitdevs.com/

## Optional 
- Name of Organiser(s) & Twitter Handle: Robby (@RawBTC) and Michael (@MichaelHawaii)
- Links showing public support: [Commitment tweet](https://twitter.com/rawbtc/status/1552158057630601216)

**Comment by 6102bitcoin** [comment]
ok - please make a pull request
