### ISSUE TITLE
Content Suggestion: The Hash Cast (THC)

### ISSUE THREAD

**Issue by zackvoell** [bitcoin-only/bitcoin-only#666]
1) Link to Content: https://econoalchemist.github.io/hashcast/
2) Briefly Describe Content: A mining-specific bi-weekly podcast hosted by Econoalchemist 
3) Suggested Section: Podcasts

**Comment by 6102bitcoin** [comment]
ok - please make a pull request

**Comment by 6102bitcoin** [comment]
https://github.com/bitcoin-only/bitcoin-only/pull/667
