### ISSUE TITLE
Content Suggestion: HODLWEEN

### ISSUE THREAD

**Issue by partyp** [bitcoin-only/bitcoin-only#669]
1) Link to Content: https://hodlween.party/
2) Briefly Describe Content: HODLween is bitcoin only celebration featuring locally sourced beef dinner and pumpkin carving contest, Bitcoin speakers and workshops, and an epic Halloween costume party! You don't need permission to be your own bank and you don't need permission to have fun! Charlotte, NC - Oct 21st-22nd, 2022
3) Suggested Section: Conferences

**Comment by 6102bitcoin** [comment]
Sorry, I missed this

**Comment by partyp** [comment]
All good! Can we put in the "looking back" section?
