### ISSUE TITLE
Meetup Suggestion: Bitcoin Meetup Plam Springs, FL by Bitcoin News

### ISSUE THREAD

**Issue by hf5pro** [bitcoin-only/bitcoin-only#692]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Bitcoin Meetup Palm Springs, FL
2. Secret Speakeasy 4 Shadowy Supercoders 2nd Ave N Palm Springs, exact location will be provided only after registration for safety reasons
3. https://bitcoinnews.com/bitcoin-meetup/
https://t.me/bitcoinnewschat

## Optional 
- Name of Organiser(s) & Twitter Handle: https://twitter.com/BitcoinNewsCom
- Links showing public support: >>>  https://www.linkedin.com/events/6989576215758016512

```
As the organiser of [>>>XXX<<<] Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_

**Bitcoin Only tweet:**
https://twitter.com/hyperfr33/status/1585569352950185985?s=20&t=eGsK3iB2vG90SQbZilqYSA


```

**Comment by 6102bitcoin** [comment]
Single event not suited to meetups page
