### ISSUE TITLE
Sovereignty Through Mathematics

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#7]
[Sovereignty Through Mathematics](https://www.amazon.com/Bitcoin-Sovereignty-mathematics-Knut-Svanholm/dp/1090109911) by Knut Svanholm.

Section: Books

Haven't read yet - Looks promising.

**Comment by PuraVlda** [comment]
Updated Pull Request to add this book

https://github.com/PuraVlda/bitcoin-only/tree/patch-2

**Comment by 6102bitcoin** [comment]
Merged. Thanks @PuraVlda
