### ISSUE TITLE
Feature Suggestion: vonBitcoin.com

### ISSUE THREAD

**Issue by bvbtc** [bitcoin-only/bitcoin-only#70]
Hi there I would like to suggest adding my merch site to the list of places to spend BTC.  My website is VonBitcoin.com. All my merch is BTC focused (or anti-shitcoin), and while i do accept Fiat, my preference and the only crypto I accept is Bitcoin/LN via opennode.  Thanks for the consideration!

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/70c46d7342dae2b1b1e2e2049d0f43209e59ec1e)
