### ISSUE TITLE
Content Suggestion: VBTC Exchange (VND-BTC

### ISSUE THREAD

**Issue by BTCxEagle** [bitcoin-only/bitcoin-only#71]
1) Link to Content: www.vbtc.exchange
2) Briefly Describe Content: VBTC is Vietnam's oldest Bitcoin Trading Platform (since 2014 - https://www.coindesk.com/first-live-bitcoin-exchange-opens-vietnam) and provides only BTC-VND orderbook
3) Suggested Section: https://bitcoin-only.com/#get-bitcoin

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/b520488d805ee521491bb42e6fbbe3ef8a01c7a1)
