### ISSUE TITLE
Content Suggestion: Vienna meetup 

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#73]
1) Link to Content: https://twitter.com/SvenSchnieders/status/1192512100452700161?s=19
2) Briefly Describe Content: Vienna
3) Suggested Section: #meetups

**Comment by SvenSchnieders** [comment]
Link to the Telegram group: https://t.me/BitcoinOnlyVienna

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/ede0d9d4dc0a1b14f39c40413dfdfac130817e4a)
