### ISSUE TITLE
Content Suggestion: Wasabi Wallet / WabiSabi coinjoins

### ISSUE THREAD

**Issue by Kruwed** [bitcoin-only/bitcoin-only#733]
1) Link to Content: [wasabiwallet.io](https://wasabiwallet.io/)
2) Briefly Describe Content: Wasabi Wallet provides network level privacy to its users by masking wallet addresses with BIP158 block filters, and masking IP addresses with Tor.  Users can also participate in non-custodial WabiSabi coinjoins to prevent previous transactions from being traced on chain to future transactions, without revealing any information to the coinjoin coordinator or other participants in the coinjoin round.
3) Suggested Section: [Privacy](https://bitcoin-only.com/privacy)

Learn more links:
Text - https://docs.wasabiwallet.io/FAQ/
Audio - https://www.whatbitcoindid.com/podcast/the-right-to-bitcoin-privacy
Video - https://www.youtube.com/watch?v=bQKU2khua-8
Download - https://wasabiwallet.io/#download

**Comment by 6102bitcoin** [comment]
Wasabi wallet was removed from bitcoin-only.com
