### ISSUE TITLE
Meetup Suggestion: Bitcoiners in Minneapolis

### ISSUE THREAD

**Issue by jeffreyweier** [bitcoin-only/bitcoin-only#736]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoiners in Minneapolis
2. Location Of Meetup: O'Shaughnessy in Minneapolis (https://twitter.com/osdistillingco)
3. At least one of the following:
- Meetup Page (or similar): https://twitter.com/BitcoinersMPLS

## Optional 
- Name of Organiser(s) & Twitter Handle: Brandon Quittem (@Bquittem)
- Links showing public support: >>>  
- Tweet your commitment 

```
As a member of the Bitcoiners in Minneapolis meetup, I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
ok, please make a pull request

**Comment by pardus79** [comment]
Already a Minneapolis meetup with same host. Link points to a telegram chat. Probably just needs an update to meetup's twitter handle or no change.

**Comment by jeffreyweier** [comment]
I see it now. Missed it as I thought they were in alphabetical order.
