### ISSUE TITLE
Wasabi wallet was removed from bitcoin-only.com

### ISSUE THREAD

**Issue by Kruwed** [bitcoin-only/bitcoin-only#744]
Wasabi wallet was removed from bitcoin-only.com

_Originally posted by @6102bitcoin in https://github.com/bitcoin-only/bitcoin-only/issues/733#issuecomment-1369190038_
      
Wasabi Wallet should not have been removed from bitcoin-only.com.  It adheres to the listing requirements: https://bitcoin-only.com/listing-requirements

-Support Bitcoin
-Not support altcoins

**Comment by 6102bitcoin** [comment]
As of March 2022, Wasabi wallet has started refusing certain blacklisted UTXOs from registering to their coordinator’s CoinJoins. As zkSNACK’s coordinator is the only one officially used by Wasabi wallet, effectively meaning that every UTXO registering to CoinJoin done by Wasabi wallet is under the company’s control.

https://twitter.com/wasabiwallet/status/1503091503207432193
https://is.muni.cz/th/kbvx1/Master_Thesis.pdf
