### ISSUE TITLE
Meetup Suggestion: Bitcoin Guadalajara Meet-Up

### ISSUE THREAD

**Issue by KatieAnanina** [bitcoin-only/bitcoin-only#80]
Thanks for making a suggestion for a new meetup.

Please note: Only suggest bitcoin-only meetups. 
Meetups which promote any coin or token other than Bitcoin are not suitable for listing. 
Altcoin's are only mentioned in the context of warnings or lessons learnt **for bitcoin**.

## Required:
1. Name of Meetup: Bitcoin Guadalajara MeetUp
2.  Location Of Meetup: Guadalajara, Mexico
3. At least one of the following:
- Telegram Group: https://t.me/BitcoinGuadalajara

## Optional 
- Name of Organiser(s) & Twitter Handle: Katie Ananina @katieAnanina
- Links showing public support:
https://twitter.com/KatieAnanina/status/1194495703944499206?s=20

```
As the organizer of Bitcoin Guadalajara Meetup I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are not promoted in talks/presentations at our meetups.
#bitcoinonlymeetups @bitcoinonly_
```

**Comment by 6102bitcoin** [comment]
[Added!](https://github.com/bitcoin-only/bitcoin-only/commit/9319de2c049882e51470399995b46075f4a004f8)
