### ISSUE TITLE
Feature Suggestion: Total Bitcoin by the TheTotalConnector

### ISSUE THREAD

**Issue by TheTotalConnector** [bitcoin-only/bitcoin-only#82]
With my Bitcoin Only-Podcast-Show (Keyvan Davani-TheTotalConnector / Total Bitcoin), I have been doing many interviews and/or panel-discussions with prominent Bitcoiners and rational (Austrian) Economists since April 2019. 
My main-podcast-platform is: anchor.fm/keyvandavani. 

(Directly to be listened on my website: keyvandavani.com/podcast or as Video-Version on my channel: youtube.com/c/keyvandavani 
or: TheTotalConnector.com).

Other Podcast-Platforms: 
Apple Podcast: https://apple.co/2IA2dhV
Google Podcast: https://bit.ly/31rSymq
Spotify: https://spoti.fi/2wOfq1k
Breaker: https://bit.ly/2IzhiQO
Overcast: https://bit.ly/2R4nnbJ
Castbox: https://bit.ly/34DbM97
Pocket-Casts: https://bit.ly/2XElbKv
Radio Public: https://bit.ly/2I86iuH

Here are my Articles on Bitcoin vs. the (criminal) State/Govs./Central Banks etc. 
medium.com/@keyvandavani 

Since June 2019, I have organizing small Bitcoin-Only-Meetups in Vienna and surrounding areas, where German-speaking and international Bitcoiners or people with a focused curiosity for Bitcoin came to the meetings for sharing knowledge and asking concrete questions (technical, Hodling, Hardware Wallet, monetary-economical aspects etc.). 
Bitcoin & Austrian Economics Meetup-Group Vienna: 
https://www.meetup.com/de-DE/Wien-Bitcoin-Meetup-Gruppe/

In order to educate to reach and educate more German-and English-speaking people on Bitcoin, the integration of my Bitcoin only Podcast & Meetup (in Vienna/ Austria,  and beyond) into 
bitcoin-only.com is really overdue and would be extremely important and effective. 

Thank you for all your work and ethos in Bitcoin!
Best wishes
Keyvan Davani

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/ef76f642e7cd0b97da1dec09f7f25514ba807bf0)

**Comment by TheTotalConnector** [comment]
Hey, please, correct my podcast link (TheTotalConnector). 
anchor.fm/keyvandavani
Thank you!
Keyvan

**Comment by 6102bitcoin** [comment]
[fixed](https://github.com/bitcoin-only/bitcoin-only/commit/5873112811dc1b31852fbc3e45ba2d574ea8e749)
