### ISSUE TITLE
Content Suggestion: Bitcoinheiros

### ISSUE THREAD

**Issue by bitcoinheiro** [bitcoin-only/bitcoin-only#84]
1) Link to Content: http://youtube.com/bitcoinheiros
2) Briefly Describe Content: Brazilian Portuguese Bitcoin Videos and Tutorials
3) Suggested Section: Videos

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/912a0fe613728ca22dee44c22d7a5fb5f38fe075)
