### ISSUE TITLE
Content Suggestion: Lightning Puzzle

### ISSUE THREAD

**Issue by JuliusHenke** [bitcoin-only/bitcoin-only#88]
1) Link to Content: https://www.lightningpuzzle.com/
2) Briefly Describe Content: Solve puzzles and win lightning prizes
3) Suggested Section: Spend Bitcoin -> Fun & Play

**Comment by 6102bitcoin** [comment]
Great idea and implementation!

[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/55f85887b1c4699c433b2ad3dcef31532dd610b8)
