### ISSUE TITLE
Content Suggestion: Bitcoin Basics

### ISSUE THREAD

**Issue by proofofgeek** [bitcoin-only/bitcoin-only#89]
1) Link to Content: https://coincompass.com/bitcoin-basics
2) Briefly Describe Content: All content is free and bitcoin-only: newsletters, video guides (2+hrs of  "bitcoin basics"), bitcoin basics podcast, e-books, etc. There's even have a free online workshop next month (Dec 2019).
3) Suggested Section: Learning

**Comment by 6102bitcoin** [comment]
Thanks for the Suggestion.

**Videos**

The intro videos look like a good foundation (though I would recommend adding steps to verify the Lubuntu Download in Video01 and I prefer protonmail over gmail for Video03). It looks like the subsequent videos will only be available for paying customers, is this correct? 

**Podcast**

I'll listen to the podcast and get back to you about that.

**Comment by proofofgeek** [comment]
Thanks for the feedback.

No the entire video series is free and on Youtube. Basically we're doing 
free content (videos, podcasts, newsletters, etc.) and paid workshops 
in-person so we can escape our boring day jobs.

Cheers,
Gordon.

**Comment by 6102bitcoin** [comment]
Videos 3 onwards have been [deleted](https://www.youtube.com/playlist?list=PL81X0bJURmxUhiKGwfSvERAKLIZepd3AX).
