### ISSUE TITLE
Koala Stickers

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#9]
A [sticker store](https://koalatickers.com/) by the creator of the RaspiBlitz Logo 

Section: Spend Bitcoin [Niche?]

**Comment by PuraVlda** [comment]
IS this link bad, i cant open for some reason.

**Comment by 6102bitcoin** [comment]
My Mistake: [https://koalastickers.com/](https://koalastickers.com/)

**Comment by 6102bitcoin** [comment]
[Merged](https://github.com/bitcoin-only/bitcoin-only/commit/292afec557f521f7e22a54b7b306a5ad89e59b78)
