### ISSUE TITLE
**Delta Bitcoin Meetup**

### ISSUE THREAD

**Issue by prayank23** [bitcoin-only/bitcoin-only#94]
1. Name of Meetup: Delta Bitcoin Meetup 

2. Location Of Meetup: Mumbai, India

3. Website: https://delta.bitcoinmeetup.info

- Name of Organiser(s) & Twitter Handle: [Prayank](https://twitter.com/prayankgahlot/status/1199549491851882496)
- Links showing public support: >>>
https://twitter.com/prayankgahlot/status/1200802173589655552

**Comment by 6102bitcoin** [comment]
Nack.

Run by the founder of an altcoin exchange

**Comment by prayank23** [comment]
- Delta is a derivatives exchange just like Bitmex
- Allows only BTC deposit/withdrawal
- Supports bech32 addresses and did it before most of the other exchanges
- Meetup is focused only on problem solving related to Bitcoin and Lightning, just organized by an exchange that allows you to speculate on altcoins as well. Similar to Trezor supporting altcoins but sponsoring or organize any Bitcoin conference
- It's fine if you don't want to list the Meetup on your website, we will organize this event and I am sure it will help Bitcoin

Cheers!
