### ISSUE TITLE
Please, change my Bitcoin only-Meetup to telegram: t.me/thetotalconnector

### ISSUE THREAD

**Issue by TheTotalConnector** [bitcoin-only/bitcoin-only#95]
Please change my listed Bitcoin only meetup to telegram on Bitcoin-only-Meetup-Site
Group: t.me/thetotalconnector

1. Name of Meetup: TheTotalConnector.TotalBitcoin. Bitcoin & AustrianEconomics Meetup Vienna
2.  Location Of Meetup: Vienna/Austria

- Website: TheTotalConnector.com

- Keyvan Davani 
@keyvandavani

As the organiser of TheTotalConnector.TotalBitcoin. Bitcoin & AustrianEconomics Meetup Vienna
I can confirm that the meetup is bitcoin-only
-The meetup is bitcoin focused.
-'Altcoins' are scams and are NOT promoted in talks/presentations at our meetups.

Thank you!
Keyvan

**Comment by 6102bitcoin** [comment]
[Updated](https://github.com/bitcoin-only/bitcoin-only/commit/c5af2ebb71dd1c020f884b51a7828c41ebc49dbf)

Please note, I see that the meetup telegram is the name of your podcast / site. 
The linked pages/chats on the meetups pages are not there for promotion of podcasts/sites thus please don't use this chat primarily for promoting these things. If you do I will have to remove the link. I think it is better to have dedicated chats for the meetup but I'll see how this goes.
