### ISSUE TITLE
Content Suggestion: lightning swap out

### ISSUE THREAD

**Issue by 6102bitcoin** [bitcoin-only/bitcoin-only#96]
1) Link to Content: https://twitter.com/bluewalletio/status/1201249697970708480?s=19
2) Briefly Describe Content: Evaluate options to swap out of lightning
3) Suggested Section: wallets?

**Comment by 6102bitcoin** [comment]
Lots of links to review - Delaying this until I have caught up with other issues.

**Comment by pardus79** [comment]
Only one of the exchanges linked in that post appeared to be bitcoin-only. Graaf. See #112

**Comment by pardus79** [comment]
Closing since only one service listed is bitcoin-only and is covered in another issue.
