### ISSUE TITLE
Content Suggestion: Add Cryptoradar

### ISSUE THREAD

**Issue by josiasmontag** [bitcoin-only/bitcoin-only#97]
1) Link to Content: https://cryptoradar.co/buy-bitcoin
2) Briefly Describe Content: Cryptoradar allows to compare Bitcoin exchanges based on prices, features and reviews. 
3) Suggested Section: Get Bitcoin / Buy

**Comment by 6102bitcoin** [comment]
Thanks for taking the time to submit an issue.

Unfortunately this site is not suitable for listing because it is not bitcoin-only.
