### ISSUE TITLE
Content Suggestion: Caravan - Open Source Multisig Coordinator

### ISSUE THREAD

**Issue by pcgeiger** [bitcoin-only/bitcoin-only#98]
1) Link to Content: https://unchained-capital.github.io/caravan/#/ 
2) Briefly Describe Content: Caravan is an open source tool that allows bitcoiners to create and spend multisignature addresses using hardware wallets right from the browser. It's the easiest way to store bitcoin in multisignature addresses without working with any company, and it can be used to spend any multisignature address, given that a user has access to the address redeem/witness script, BIP32 paths, and private keys. 
3) Suggested Section: on-chain wallets

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/e39c968ad15f0b69a68374493f4d6421736bec5d)

Apologies this took so long to add.
