### ISSUE TITLE
Content Suggestion: MtSocks

### ISSUE THREAD

**Issue by dannmat** [bitcoin-only/bitcoin-only#99]
1) Link to Content: https://www.mtsocks.com
2) Briefly Describe Content: Limited Edition Bitcoin Socks
3) Suggested Section: Spend Bitcoin - Stores

**Comment by 6102bitcoin** [comment]
[Added](https://github.com/bitcoin-only/bitcoin-only/commit/5ceac031535e4a405d06760357825d6216039a3e)
